import json
topics = [
    "A16Z",
    "Algorand",
    "ApeCoin",
    "Aptos",
    "Artificial Intelligence",
    "Avalanche",
    "KuCoin",
    "BNB",
    "Binance",
    "Binance USD",
    "Bitcoin",
    "BlockFi",
    "Blockstream",
    "Cardano",
    "Chainlink",
    "Circle",
    "Coinbase",
    "Cosmos",
    "Crypto Gaming",
    "Dai",
    "Digital Currency Group",
    "Dogecoin",
    "Dragonfly",
    "Ethereum",
    "FTX",
    "Filecoin",
    "Gemini",
    "Goldman Sachs",
    "HSBC",
    "Hedera",
    "IBM",
    "IMF",
    "JPMorgan",
    "Kraken",
    "KuCoin",
    "Litecoin",
    "Marathon",
    "Microsoft",
    "Miners",
    "Multicoin",
    "NFT",
    "OKB",
    "Optimism",
    "Pantera",
    "PayPal",
    "Polkadot",
    "Polychain",
    "Polygon",
    "Regulation",
    "Riot",
    "Robinhood",
    "Santander",
    "Sequoia",
    "Seven Seven Six",
    "Shiba Inu",
    "Solana",
    "Stablecoins",
    "Stronghold Digital",
    "TRON",
    "Tether",
    "Tezos",
    "TrueUSD",
    "USDC",
    "USDT",
    "Union Square Ventures",
    "Uniswap",
    "VeChain",
    "Web3",
    "XRP"
]

top75 = [
    "Aave",
    "Arbitrum",
    "Astar",
    "Axie Infinity",
    "Bitcoin Cash",
    "Bitcoin SV",
    "Bittensor",
    "Celestia",
    "Cosmos Hub",
    "Cronos",
    "Ethereum Classic",
    "Fantom",
    "First Digital USD",
    "Flare",
    "Flow",
    "Helium",
    "Immutable",
    "Injective",
    "Internet Computer",
    "Kaspa",
    "KuCoin",
    "LEO Token",
    "Lido DAO",
    "Lido Staked Ether",
    "Maker",
    "Mantle",
    "Mantle Staked Ether",
    "Mina Protocol",
    "Monero",
    "MultiversX",
    "NEAR Protocol",
    "ORDI",
    "Osmosis",
    "Quant",
    "Render",
    "Rocket Pool ETH",
    "Sei",
    "Shiba Inu",
    "Stacks",
    "Stellar",
    "Sui",
    "Synthetix Network",
    "THORChain",
    "The Graph",
    "The Sandbox",
    "Theta Network",
    "Tokenize Xchange",
    "Toncoin",
    "Wrapped Bitcoin",
    "dYdX",
    "Algorand",
    "Aptos",
    "Avalanche",
    "BNB",
    "Bitcoin",
    "Cardano",
    "Chainlink",
    "Dai",
    "Dogecoin",
    "Ethereum",
    "Filecoin",
    "Hedera",
    "Litecoin",
    "OKB",
    "Optimism",
    "Polkadot",
    "Polygon",
    "Solana",
    "TRON",
    "Tether",
    "TrueUSD",
    "USDC",
    "Uniswap",
    "VeChain",
    "XRP"
]

not_exist = list()
for name in top75:
    if name not in topics:
        not_exist.append(name)


with open("not_exist_names.json", "w") as f:
    f.write(json.dumps(not_exist))

