names = [
    "Aave",
    "Arbitrum",
    "Astar",
    "Axie Infinity",
    "Bitcoin Cash",
    "Bitcoin SV",
    "Bittensor",
    "Celestia",
    "Cosmos Hub",
    "Cronos",
    "Ethereum Classic",
    "Fantom",
    "First Digital USD",
    "Flare",
    "Flow",
    "Helium",
    "Immutable",
    "Injective",
    "Internet Computer",
    "Kaspa",
    "LEO Token",
    "Lido DAO",
    "Lido Staked Ether",
    "Maker",
    "Mantle",
    "Mantle Staked Ether",
    "Mina Protocol",
    "Monero",
    "MultiversX",
    "NEAR Protocol",
    "ORDI",
    "Osmosis",
    "Quant",
    "Render",
    "Rocket Pool ETH",
    "Sei",
    "Stacks",
    "Stellar",
    "Sui",
    "Synthetix Network",
    "THORChain",
    "The Graph",
    "The Sandbox",
    "Theta Network",
    "Tokenize Xchange",
    "Toncoin",
    "Wrapped Bitcoin",
    "dYdX"
]

print(len(names))
