import json

stablecoin_list = [
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Aave",
        "NewsPageMetaTitle": "Aave (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Aave news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Aave News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Algorand",
        "NewsPageMetaTitle": "Algorand (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Algorand news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Algorand News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Aptos",
        "NewsPageMetaTitle": "Aptos (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Aptos news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Aptos News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Arbitrum",
        "NewsPageMetaTitle": "Arbitrum (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Arbitrum news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Arbitrum News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Astar",
        "NewsPageMetaTitle": "Astar (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Astar news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Astar News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Avalanche",
        "NewsPageMetaTitle": "Avalanche (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Avalanche news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Avalanche News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Axie Infinity",
        "NewsPageMetaTitle": "Axie Infinity (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Axie Infinity news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Axie Infinity News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "BNB",
        "NewsPageMetaTitle": "BNB (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest BNB news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest BNB News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin",
        "NewsPageMetaTitle": "Bitcoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bitcoin news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bitcoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin Cash",
        "NewsPageMetaTitle": "Bitcoin Cash (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Bitcoin Cash news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Bitcoin Cash News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin SV",
        "NewsPageMetaTitle": "Bitcoin SV (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Bitcoin SV News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bittensor",
        "NewsPageMetaTitle": "Bittensor (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bittensor news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bittensor News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cardano",
        "NewsPageMetaTitle": "Cardano (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Cardano news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Cardano News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Celestia",
        "NewsPageMetaTitle": "Celestia (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Celestia News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Chainlink",
        "NewsPageMetaTitle": "Chainlink (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Chainlink news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Chainlink News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cosmos Hub",
        "NewsPageMetaTitle": "Cosmos Hub (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Cosmos Hub News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cronos",
        "NewsPageMetaTitle": "Cronos (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Cronos news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Cronos News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Dai",
        "NewsPageMetaTitle": "Dai (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Dai news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Dai News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Dogecoin",
        "NewsPageMetaTitle": "Dogecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Dogecoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Dogecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Ethereum",
        "NewsPageMetaTitle": "Ethereum (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Ethereum news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Ethereum News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Ethereum Classic",
        "NewsPageMetaTitle": "Ethereum Classic (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Ethereum Classic news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Ethereum Classic News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Fantom",
        "NewsPageMetaTitle": "Fantom (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Fantom News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Filecoin",
        "NewsPageMetaTitle": "Filecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Filecoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Filecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "First Digital USD",
        "NewsPageMetaTitle": "First Digital USD (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking First Digital USD news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest First Digital USD News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Flow",
        "NewsPageMetaTitle": "Flow (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Flow news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Flow News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Hedera",
        "NewsPageMetaTitle": "Hedera (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Hedera News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Helium",
        "NewsPageMetaTitle": "Helium (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Helium news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Helium News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Immutable",
        "NewsPageMetaTitle": "Immutable (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Immutable news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Immutable News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Injective",
        "NewsPageMetaTitle": "Injective (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Injective news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Injective News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Internet Computer",
        "NewsPageMetaTitle": "Internet Computer (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Internet Computer news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Internet Computer News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Kaspa",
        "NewsPageMetaTitle": "Kaspa (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Kaspa news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Kaspa News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "KuCoin",
        "NewsPageMetaTitle": "KuCoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking KuCoin news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest KuCoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "LEO Token",
        "NewsPageMetaTitle": "LEO Token (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking LEO Token news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest LEO Token News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Lido DAO",
        "NewsPageMetaTitle": "Lido DAO (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Lido DAO news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Lido DAO News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Lido Staked Ether",
        "NewsPageMetaTitle": "Lido Staked Ether (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Lido Staked Ether news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Lido Staked Ether News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Litecoin",
        "NewsPageMetaTitle": "Litecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Litecoin news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Litecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Maker",
        "NewsPageMetaTitle": "Maker (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Maker news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Maker News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Mantle",
        "NewsPageMetaTitle": "Mantle (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Mantle news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Mantle News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Mina Protocol",
        "NewsPageMetaTitle": "Mina Protocol (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Mina Protocol news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Mina Protocol News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Monero",
        "NewsPageMetaTitle": "Monero (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Monero news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Monero News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "MultiversX",
        "NewsPageMetaTitle": "MultiversX (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest MultiversX News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "NEAR Protocol",
        "NewsPageMetaTitle": "NEAR Protocol (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking NEAR Protocol news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest NEAR Protocol News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "OKB",
        "NewsPageMetaTitle": "OKB (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in OKB news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest OKB News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "ORDI",
        "NewsPageMetaTitle": "ORDI (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in ORDI news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest ORDI News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Optimism",
        "NewsPageMetaTitle": "Optimism (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Optimism news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Optimism News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Osmosis",
        "NewsPageMetaTitle": "Osmosis (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Osmosis news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Osmosis News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Polkadot",
        "NewsPageMetaTitle": "Polkadot (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Polkadot news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Polkadot News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Polygon",
        "NewsPageMetaTitle": "Polygon (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Polygon news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Polygon News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Quant",
        "NewsPageMetaTitle": "Quant (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Quant news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Quant News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Render",
        "NewsPageMetaTitle": "Render (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Render news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Render News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Rocket Pool ETH",
        "NewsPageMetaTitle": "Rocket Pool ETH (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Rocket Pool ETH news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Rocket Pool ETH News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "SATS (Ordinals)",
        "NewsPageMetaTitle": "SATS (Ordinals) (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking SATS (Ordinals) news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest SATS (Ordinals) News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Sei",
        "NewsPageMetaTitle": "Sei (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Sei news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Sei News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Shiba Inu",
        "NewsPageMetaTitle": "Shiba Inu (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Shiba Inu news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Shiba Inu News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Solana",
        "NewsPageMetaTitle": "Solana (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Solana news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Solana News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Stacks",
        "NewsPageMetaTitle": "Stacks (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Stacks news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Stacks News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Stellar",
        "NewsPageMetaTitle": "Stellar (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Stellar news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Stellar News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Sui",
        "NewsPageMetaTitle": "Sui (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Sui news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Sui News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Synthetix Network",
        "NewsPageMetaTitle": "Synthetix Network (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Synthetix Network news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Synthetix Network News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "THORChain",
        "NewsPageMetaTitle": "THORChain (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest THORChain news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest THORChain News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "TRON",
        "NewsPageMetaTitle": "TRON (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in TRON news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest TRON News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Tether",
        "NewsPageMetaTitle": "Tether (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Tether news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Tether News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "The Graph",
        "NewsPageMetaTitle": "The Graph (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking The Graph news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest The Graph News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "The Sandbox",
        "NewsPageMetaTitle": "The Sandbox (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest The Sandbox news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest The Sandbox News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Theta Network",
        "NewsPageMetaTitle": "Theta Network (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Theta Network news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Theta Network News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Tokenize Xchange",
        "NewsPageMetaTitle": "Tokenize Xchange (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Tokenize Xchange News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Toncoin",
        "NewsPageMetaTitle": "Toncoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Toncoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Toncoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "TrueUSD",
        "NewsPageMetaTitle": "TrueUSD (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest TrueUSD news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest TrueUSD News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "USDC",
        "NewsPageMetaTitle": "USDC (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with USDC news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest USDC News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Uniswap",
        "NewsPageMetaTitle": "Uniswap (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Uniswap news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Uniswap News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "VeChain",
        "NewsPageMetaTitle": "VeChain (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in VeChain news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest VeChain News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "WhiteBIT Coin",
        "NewsPageMetaTitle": "WhiteBIT Coin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest WhiteBIT Coin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Wrapped Bitcoin",
        "NewsPageMetaTitle": "Wrapped Bitcoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Wrapped Bitcoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "XRP",
        "NewsPageMetaTitle": "XRP (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in XRP news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest XRP News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "dYdX",
        "NewsPageMetaTitle": "dYdX (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest dYdX news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest dYdX News",
    },
]
names = list()
for item in stablecoin_list:
    names.append(item["NewsTag"])

with open("stablecoin.json", "w") as file:
    file.write(json.dumps(names))


response = [
    {
        "symbol": "tether",
        "displaySymbol": "usdt",
        "name": "Tether",
        "slug": "tether-usdt",
        "logo": "https://assets.coingecko.com/coins/images/325/large/Tether.png?1696501661",
        "temporaryDataDelay": False,
        "price": 1,
        "percentage": 0.00015502402872446852,
        "percentage_1h": 0,
        "percentage_7d": -0.000999000999000889,
        "changeValue": 0.00015500000000001624,
        "marketCap": 97870631885,
        "volume": 28659626913,
        "FullCount": None,
        "rank": 3,
        "Status": "active",
    },
    {
        "symbol": "usd-coin",
        "displaySymbol": "usdc",
        "name": "USDC",
        "slug": "usdc-usdc",
        "logo": "https://assets.coingecko.com/coins/images/6319/large/usdc.png?1696506694",
        "temporaryDataDelay": False,
        "price": 1.001,
        "percentage": 0.001152175130619785,
        "percentage_1h": 0,
        "percentage_7d": 0,
        "changeValue": 0.0011519999999999309,
        "marketCap": 28182280865,
        "volume": 3489172942,
        "FullCount": None,
        "rank": 8,
        "Status": "active",
    },
    {
        "symbol": "dai",
        "displaySymbol": "dai",
        "name": "Dai",
        "slug": "dai-dai",
        "logo": "https://assets.coingecko.com/coins/images/9956/large/Badge_Dai.png?1696509996",
        "temporaryDataDelay": False,
        "price": 0.999199,
        "percentage": 0.00045657391340905607,
        "percentage_1h": 0,
        "percentage_7d": -0.0002221286124666737,
        "changeValue": 0.00045599999999990093,
        "marketCap": 4946688137,
        "volume": 112756148,
        "FullCount": None,
        "rank": 23,
        "Status": "active",
    },
    {
        "symbol": "first-digital-usd",
        "displaySymbol": "fdusd",
        "name": "First Digital USD",
        "slug": "first-digital-usd-fdusd",
        "logo": "https://assets.coingecko.com/coins/images/31079/large/firstfigital.jpeg?1696529912",
        "temporaryDataDelay": False,
        "price": 1.002,
        "percentage": 0,
        "percentage_1h": 0,
        "percentage_7d": 0.0024781820928582447,
        "changeValue": 0,
        "marketCap": 3311489826,
        "volume": 3056367011,
        "FullCount": None,
        "rank": 37,
        "Status": "active",
    },
    {
        "symbol": "true-usd",
        "displaySymbol": "tusd",
        "name": "TrueUSD",
        "slug": "trueusd-tusd",
        "logo": "https://assets.coingecko.com/coins/images/3449/large/tusd.png?1696504140",
        "temporaryDataDelay": False,
        "price": 0.975529,
        "percentage": 0.002141879758876734,
        "percentage_1h": 0,
        "percentage_7d": -0.002003095693344275,
        "changeValue": 0.0020850000000000035,
        "marketCap": 1254617413,
        "volume": 39503593,
        "FullCount": None,
        "rank": 70,
        "Status": "active",
    },
    {
        "symbol": "usdd",
        "displaySymbol": "usdd",
        "name": "USDD",
        "slug": "usdd-usdd",
        "logo": "https://assets.coingecko.com/coins/images/25380/large/UUSD.jpg?1696524513",
        "temporaryDataDelay": False,
        "price": 1,
        "percentage": 0.00032310436270911725,
        "percentage_1h": 0,
        "percentage_7d": 0.00014802190724230886,
        "changeValue": 0.0003229999999999622,
        "marketCap": 738427496,
        "volume": 8928559,
        "FullCount": None,
        "rank": 115,
        "Status": "active",
    },
    {
        "symbol": "frax",
        "displaySymbol": "frax",
        "name": "Frax",
        "slug": "frax-frax",
        "logo": "https://assets.coingecko.com/coins/images/13422/large/FRAX_icon.png?1696513182",
        "temporaryDataDelay": False,
        "price": 0.999216,
        "percentage": 0.0004836127373382187,
        "percentage_1h": 0,
        "percentage_7d": -0.0007200460829493627,
        "changeValue": 0.0004830000000000112,
        "marketCap": 648475632,
        "volume": 11334932,
        "FullCount": None,
        "rank": 126,
        "Status": "active",
    },
    {
        "symbol": "tether-gold",
        "displaySymbol": "xaut",
        "name": "Tether Gold",
        "slug": "tether-gold-xaut",
        "logo": "https://assets.coingecko.com/coins/images/10481/large/Tether_Gold.png?1696510471",
        "temporaryDataDelay": False,
        "price": 2034.57,
        "percentage": 0.002187052060705387,
        "percentage_1h": 0,
        "percentage_7d": 0.010820800977747293,
        "changeValue": 4.439999999999827,
        "marketCap": 500958789,
        "volume": 7108945,
        "FullCount": None,
        "rank": 145,
        "Status": "active",
    },
    {
        "symbol": "ethena-usde",
        "displaySymbol": "usde",
        "name": "Ethena USDe",
        "slug": "ethena-usde-usde",
        "logo": "https://assets.coingecko.com/coins/images/33613/large/3466ef_3c088c66c7d941e8856339d0bddf33cc_mv2.png?1702514458",
        "temporaryDataDelay": False,
        "price": 1.001,
        "percentage": 0,
        "percentage_1h": 0,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 436171134,
        "volume": 24218272,
        "FullCount": None,
        "rank": 163,
        "Status": "active",
    },
    {
        "symbol": "pax-gold",
        "displaySymbol": "paxg",
        "name": "PAX Gold",
        "slug": "pax-gold-paxg",
        "logo": "https://assets.coingecko.com/coins/images/9519/large/paxgold.png?1696509604",
        "temporaryDataDelay": False,
        "price": 2008.01,
        "percentage": 0.0006228946161972533,
        "percentage_1h": 0,
        "percentage_7d": 0.009501736957734912,
        "changeValue": 1.25,
        "marketCap": 405032226,
        "volume": 7024383,
        "FullCount": None,
        "rank": 178,
        "Status": "active",
    },
    {
        "symbol": "paypal-usd",
        "displaySymbol": "pyusd",
        "name": "PayPal USD",
        "slug": "paypal-usd-pyusd",
        "logo": "https://assets.coingecko.com/coins/images/31212/large/PYUSD_Logo_%282%29.png?1696530039",
        "temporaryDataDelay": False,
        "price": 1,
        "percentage": 0.0012114658737072302,
        "percentage_1h": 0,
        "percentage_7d": 0,
        "changeValue": 0.0012100000000000444,
        "marketCap": 304869346,
        "volume": 4936199,
        "FullCount": None,
        "rank": 216,
        "Status": "active",
    },
    {
        "symbol": "terrausd",
        "displaySymbol": "ustc",
        "name": "TerraClassicUSD",
        "slug": "terraclassicusd-ustc",
        "logo": "https://assets.coingecko.com/coins/images/12681/large/UST.png?1696512486",
        "temporaryDataDelay": False,
        "price": 0.03256149,
        "percentage": 0.022536540819197693,
        "percentage_1h": 0,
        "percentage_7d": 0.03845885215363499,
        "changeValue": 0.0007176500000000002,
        "marketCap": 291593213,
        "volume": 31462576,
        "FullCount": None,
        "rank": 224,
        "Status": "active",
    },
    {
        "symbol": "paxos-standard",
        "displaySymbol": "usdp",
        "name": "Pax Dollar",
        "slug": "pax-dollar-usdp",
        "logo": "https://assets.coingecko.com/coins/images/6013/large/Pax_Dollar.png?1696506427",
        "temporaryDataDelay": False,
        "price": 0.999959,
        "percentage": 0.0003881665234386101,
        "percentage_1h": 0,
        "percentage_7d": 0.00018104019092248256,
        "changeValue": 0.00038800000000005497,
        "marketCap": 215343362,
        "volume": 5496615,
        "FullCount": None,
        "rank": 266,
        "Status": "active",
    },
    {
        "symbol": "alchemix-usd",
        "displaySymbol": "alusd",
        "name": "Alchemix USD",
        "slug": "alchemix-usd-alusd",
        "logo": "https://assets.coingecko.com/coins/images/14114/large/Alchemix_USD.png?1696513835",
        "temporaryDataDelay": False,
        "price": 0.983139,
        "percentage": -0.003327179774153234,
        "percentage_1h": 0,
        "percentage_7d": 0.002039468453978982,
        "changeValue": -0.003282000000000007,
        "marketCap": 164584363,
        "volume": 13280.77,
        "FullCount": None,
        "rank": 317,
        "Status": "active",
    },
    {
        "symbol": "crvusd",
        "displaySymbol": "crvusd",
        "name": "crvUSD",
        "slug": "crvusd-crvusd",
        "logo": "https://assets.coingecko.com/coins/images/30118/large/crvusd.jpeg?1696529040",
        "temporaryDataDelay": False,
        "price": 0.997822,
        "percentage": 0.00032581551623716133,
        "percentage_1h": 0,
        "percentage_7d": 0.00013531297892023874,
        "changeValue": 0.0003250000000000197,
        "marketCap": 149159654,
        "volume": 11179563,
        "FullCount": None,
        "rank": 337,
        "Status": "active",
    },
    {
        "symbol": "liquity-usd",
        "displaySymbol": "lusd",
        "name": "Liquity USD",
        "slug": "liquity-usd-lusd",
        "logo": "https://assets.coingecko.com/coins/images/14666/large/Group_3.png?1696514341",
        "temporaryDataDelay": False,
        "price": 0.99597,
        "percentage": 0.0012908596280635928,
        "percentage_1h": 0,
        "percentage_7d": -0.000154599226602298,
        "changeValue": 0.0012840000000000629,
        "marketCap": 148511759,
        "volume": 4775471,
        "FullCount": None,
        "rank": 339,
        "Status": "active",
    },
    {
        "symbol": "stasis-eurs",
        "displaySymbol": "eurs",
        "name": "STASIS EURO",
        "slug": "stasis-euro-eurs",
        "logo": "https://assets.coingecko.com/coins/images/5164/large/EURS_300x300.png?1696505680",
        "temporaryDataDelay": False,
        "price": 1.083,
        "percentage": -0.0009225092250923541,
        "percentage_1h": 0,
        "percentage_7d": 0.02751423149905115,
        "changeValue": -0.001000000000000112,
        "marketCap": 134409530,
        "volume": 1427312,
        "FullCount": None,
        "rank": 359,
        "Status": "active",
    },
    {
        "symbol": "tor",
        "displaySymbol": "tor",
        "name": "TOR",
        "slug": "tor-tor",
        "logo": "https://assets.coingecko.com/coins/images/23609/large/tor.png?1696522816",
        "temporaryDataDelay": False,
        "price": 7.8,
        "percentage": 0,
        "percentage_1h": 0,
        "percentage_7d": 0.015625000000000014,
        "changeValue": 0,
        "marketCap": 133211941,
        "volume": 0,
        "FullCount": None,
        "rank": 364,
        "Status": "active",
    },
    {
        "symbol": "usdx",
        "displaySymbol": "usdx",
        "name": "USDX",
        "slug": "usdx-usdx",
        "logo": "https://assets.coingecko.com/coins/images/13056/large/USDX_coin.png?1696512841",
        "temporaryDataDelay": False,
        "price": 0.893162,
        "percentage": -0.00040289998455553076,
        "percentage_1h": 0,
        "percentage_7d": 0.000127652712956144,
        "changeValue": -0.00036000000000002697,
        "marketCap": 98608474,
        "volume": 324959,
        "FullCount": None,
        "rank": 429,
        "Status": "active",
    },
    {
        "symbol": "prisma-mkusd",
        "displaySymbol": "mkusd",
        "name": "Prisma mkUSD",
        "slug": "prisma-mkusd-mkusd",
        "logo": "https://assets.coingecko.com/coins/images/31519/large/mkUSD_200.png?1696530329",
        "temporaryDataDelay": False,
        "price": 0.992423,
        "percentage": -0.0004371223650535117,
        "percentage_1h": 0,
        "percentage_7d": -0.0004713508330722234,
        "changeValue": -0.00043399999999993444,
        "marketCap": 92124770,
        "volume": 4327254,
        "FullCount": None,
        "rank": 447,
        "Status": "active",
    },
    {
        "symbol": "binance-usd",
        "displaySymbol": "busd",
        "name": "BUSD",
        "slug": "busd-busd",
        "logo": "https://assets.coingecko.com/coins/images/9576/large/BUSDLOGO.jpg?1696509654",
        "temporaryDataDelay": False,
        "price": 1.002,
        "percentage": 0.0009990009990011109,
        "percentage_1h": 0,
        "percentage_7d": -0.000997008973080648,
        "changeValue": 0.001000000000000112,
        "marketCap": 84691904,
        "volume": 28762251,
        "FullCount": None,
        "rank": 476,
        "Status": "active",
    },
    {
        "symbol": "helio-protocol-hay",
        "displaySymbol": "lisusd",
        "name": "Lista USD",
        "slug": "lista-usd-lisusd",
        "logo": "https://assets.coingecko.com/coins/images/26947/large/HAY.png?1696526002",
        "temporaryDataDelay": False,
        "price": 0.986298,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.0019802279073277184,
        "changeValue": 0,
        "marketCap": 57900044,
        "volume": 2504823,
        "FullCount": None,
        "rank": 594,
        "Status": "active",
    },
    {
        "symbol": "magic-internet-money",
        "displaySymbol": "mim",
        "name": "Magic Internet Money",
        "slug": "magic-internet-money-mim",
        "logo": "https://assets.coingecko.com/coins/images/16786/large/mimlogopng.png?1696516358",
        "temporaryDataDelay": False,
        "price": 0.994562,
        "percentage": -0.00016393854818840285,
        "percentage_1h": None,
        "percentage_7d": -0.00028157909556800334,
        "changeValue": -0.00016300000000002424,
        "marketCap": 55417808,
        "volume": 95172,
        "FullCount": None,
        "rank": 607,
        "Status": "active",
    },
    {
        "symbol": "nusd",
        "displaySymbol": "susd",
        "name": "sUSD",
        "slug": "susd-susd",
        "logo": "https://assets.coingecko.com/coins/images/5013/large/sUSD.png?1696505546",
        "temporaryDataDelay": False,
        "price": 0.995274,
        "percentage": -0.00032864883118602654,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0003269999999999662,
        "marketCap": 52834796,
        "volume": 1117662,
        "FullCount": None,
        "rank": 627,
        "Status": "active",
    },
    {
        "symbol": "bean",
        "displaySymbol": "bean",
        "name": "Bean",
        "slug": "bean-bean",
        "logo": "https://assets.coingecko.com/coins/images/18447/large/bean-logo-coingecko.png?1696517934",
        "temporaryDataDelay": False,
        "price": 0.985233,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.00003244636463836195,
        "changeValue": 0,
        "marketCap": 40952038,
        "volume": 825.16,
        "FullCount": None,
        "rank": 715,
        "Status": "active",
    },
    {
        "symbol": "celo-dollar",
        "displaySymbol": "cusd",
        "name": "Celo Dollar",
        "slug": "celo-dollar-cusd",
        "logo": "https://assets.coingecko.com/coins/images/13161/large/icon-celo-dollar-color-1000-circle-cropped.png?1696512945",
        "temporaryDataDelay": False,
        "price": 0.992948,
        "percentage": -0.001939060939060799,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0019409999999998595,
        "marketCap": 39379205,
        "volume": 4540980,
        "FullCount": None,
        "rank": 733,
        "Status": "active",
    },
    {
        "symbol": "tether-eurt",
        "displaySymbol": "eurt",
        "name": "Euro Tether",
        "slug": "euro-tether-eurt",
        "logo": "https://assets.coingecko.com/coins/images/17385/large/Tether_new.png?1696516934",
        "temporaryDataDelay": False,
        "price": 1.081,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 39328546,
        "volume": 2346810,
        "FullCount": None,
        "rank": 734,
        "Status": "active",
    },
    {
        "symbol": "token-dforce-usd",
        "displaySymbol": "usx",
        "name": "dForce USD",
        "slug": "dforce-usd-usx",
        "logo": "https://assets.coingecko.com/coins/images/17422/large/usx_32.png?1696516969",
        "temporaryDataDelay": False,
        "price": 1.19,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.0019361084220716378,
        "changeValue": 0,
        "marketCap": 38120457,
        "volume": 12721.78,
        "FullCount": None,
        "rank": 743,
        "Status": "active",
    },
    {
        "symbol": "bilira",
        "displaySymbol": "tryb",
        "name": "BiLira",
        "slug": "bilira-tryb",
        "logo": "https://assets.coingecko.com/coins/images/10119/large/JBs9jiXO_400x400.jpg?1696510144",
        "temporaryDataDelay": False,
        "price": 0.03206202,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.0006096890281262536,
        "changeValue": 0,
        "marketCap": 36933548,
        "volume": 743.54,
        "FullCount": None,
        "rank": 755,
        "Status": "active",
    },
    {
        "symbol": "eusd-new",
        "displaySymbol": "eusd",
        "name": "eUSD",
        "slug": "eusd-eusd",
        "logo": "https://assets.coingecko.com/coins/images/31603/large/eusd.png?1696530419",
        "temporaryDataDelay": False,
        "price": 0.900942,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.00003309537756858685,
        "changeValue": 0,
        "marketCap": 35834437,
        "volume": 14366.64,
        "FullCount": None,
        "rank": 773,
        "Status": "active",
    },
    {
        "symbol": "gho",
        "displaySymbol": "gho",
        "name": "GHO",
        "slug": "gho-gho",
        "logo": "https://assets.coingecko.com/coins/images/30663/large/ghoaave.jpeg?1696529533",
        "temporaryDataDelay": False,
        "price": 0.992145,
        "percentage": -0.001864879798837176,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.001862999999999948,
        "marketCap": 34165694,
        "volume": 375483,
        "FullCount": None,
        "rank": 789,
        "Status": "active",
    },
    {
        "symbol": "flex-usd",
        "displaySymbol": "flexusd",
        "name": "flexUSD",
        "slug": "flexusd-flexusd",
        "logo": "https://assets.coingecko.com/coins/images/13323/large/flexUSD_2x.png?1696513092",
        "temporaryDataDelay": False,
        "price": 0.192319,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0029991798161320264,
        "changeValue": 0,
        "marketCap": 31992245,
        "volume": 5.68,
        "FullCount": None,
        "rank": 812,
        "Status": "active",
    },
    {
        "symbol": "xsgd",
        "displaySymbol": "xsgd",
        "name": "XSGD",
        "slug": "xsgd-xsgd",
        "logo": "https://assets.coingecko.com/coins/images/12832/large/StraitsX_Singapore_Dollar_%28XSGD%29_Token_Logo.png?1696512623",
        "temporaryDataDelay": False,
        "price": 0.745258,
        "percentage": 0.0008269204351702506,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0006140000000000034,
        "marketCap": 31845767,
        "volume": 13856118,
        "FullCount": None,
        "rank": 815,
        "Status": "active",
    },
    {
        "symbol": "gemini-dollar",
        "displaySymbol": "gusd",
        "name": "Gemini Dollar",
        "slug": "gemini-dollar-gusd",
        "logo": "https://assets.coingecko.com/coins/images/5992/large/gemini-dollar-gusd.png?1696506408",
        "temporaryDataDelay": False,
        "price": 1,
        "percentage": 0.0013678573577488838,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0013640000000000319,
        "marketCap": 31374120,
        "volume": 128306,
        "FullCount": None,
        "rank": 820,
        "Status": "active",
    },
    {
        "symbol": "mimatic",
        "displaySymbol": "mimatic",
        "name": "MAI",
        "slug": "mai-mimatic",
        "logo": "https://assets.coingecko.com/coins/images/15264/large/mimatic-red.png?1696514916",
        "temporaryDataDelay": False,
        "price": 0.882684,
        "percentage": 0.00010842051227578137,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.00009799999999993148,
        "marketCap": 24319117,
        "volume": 23472,
        "FullCount": None,
        "rank": 918,
        "Status": "active",
    },
    {
        "symbol": "verified-usd-foundation-usdv",
        "displaySymbol": "usdv",
        "name": "Verified USD",
        "slug": "verified-usd-usdv",
        "logo": "https://assets.coingecko.com/coins/images/32948/large/usdv_%281%29.png?1699933314",
        "temporaryDataDelay": False,
        "price": 0.998616,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 23719846,
        "volume": 5492957,
        "FullCount": None,
        "rank": 929,
        "Status": "active",
    },
    {
        "symbol": "ageur",
        "displaySymbol": "ageur",
        "name": "agEUR",
        "slug": "ageur-ageur",
        "logo": "https://assets.coingecko.com/coins/images/19479/large/agEUR.png?1696518915",
        "temporaryDataDelay": False,
        "price": 1.083,
        "percentage": -0.000928505106777985,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0009999999999998899,
        "marketCap": 21202084,
        "volume": 742312,
        "FullCount": None,
        "rank": 974,
        "Status": "active",
    },
    {
        "symbol": "zusd",
        "displaySymbol": "zusd",
        "name": "ZUSD",
        "slug": "zusd-zusd",
        "logo": "https://assets.coingecko.com/coins/images/14192/large/icon_zusd_200_200.png?1696513910",
        "temporaryDataDelay": False,
        "price": 0.997828,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.0006366463675064238,
        "changeValue": 0,
        "marketCap": 18606720,
        "volume": 2683.01,
        "FullCount": None,
        "rank": 1024,
        "Status": "active",
    },
    {
        "symbol": "gyen",
        "displaySymbol": "gyen",
        "name": "GYEN",
        "slug": "gyen-gyen",
        "logo": "https://assets.coingecko.com/coins/images/14191/large/icon_gyen_200_200.png?1696513909",
        "temporaryDataDelay": False,
        "price": 0.00665855,
        "percentage": 0.0020369085254581688,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.000012680000000000156,
        "marketCap": 13812229,
        "volume": 19785.27,
        "FullCount": None,
        "rank": 1151,
        "Status": "active",
    },
    {
        "symbol": "fei-usd",
        "displaySymbol": "fei",
        "name": "Fei USD",
        "slug": "fei-usd-fei",
        "logo": "https://assets.coingecko.com/coins/images/14570/large/ZqsF51Re_400x400.png?1696514251",
        "temporaryDataDelay": False,
        "price": 0.969844,
        "percentage": 0.0008235519212052297,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0007920000000000149,
        "marketCap": 13401592,
        "volume": 19074.86,
        "FullCount": None,
        "rank": 1168,
        "Status": "active",
    },
    {
        "symbol": "origin-dollar",
        "displaySymbol": "ousd",
        "name": "Origin Dollar",
        "slug": "origin-dollar-ousd",
        "logo": "https://assets.coingecko.com/coins/images/12589/large/ousd-logo-200x200.png?1696512399",
        "temporaryDataDelay": False,
        "price": 0.99761,
        "percentage": -0.0010698601675747166,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0010689999999999866,
        "marketCap": 13129505,
        "volume": 256683,
        "FullCount": None,
        "rank": 1173,
        "Status": "active",
    },
    {
        "symbol": "husd",
        "displaySymbol": "husd",
        "name": "HUSD",
        "slug": "husd-husd",
        "logo": "https://assets.coingecko.com/coins/images/9567/large/HUSD.jpg?1696509647",
        "temporaryDataDelay": False,
        "price": 0.058362,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.002119136131354078,
        "changeValue": 0,
        "marketCap": 10961766,
        "volume": 12425.74,
        "FullCount": None,
        "rank": 1258,
        "Status": "active",
    },
    {
        "symbol": "celo-euro",
        "displaySymbol": "ceur",
        "name": "Celo Euro",
        "slug": "celo-euro-ceur",
        "logo": "https://assets.coingecko.com/coins/images/16756/large/CEUR.png?1696516329",
        "temporaryDataDelay": False,
        "price": 1.073,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0018450184501845033,
        "changeValue": 0,
        "marketCap": 10450659,
        "volume": 1265769,
        "FullCount": None,
        "rank": 1282,
        "Status": "active",
    },
    {
        "symbol": "usk",
        "displaySymbol": "usk",
        "name": "USK",
        "slug": "usk-usk",
        "logo": "https://assets.coingecko.com/coins/images/27274/large/usk.png?1696526326",
        "temporaryDataDelay": False,
        "price": 1.001,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0000953910077406853,
        "changeValue": 0,
        "marketCap": 7625696,
        "volume": 628441,
        "FullCount": None,
        "rank": 1421,
        "Status": "active",
    },
    {
        "symbol": "vai",
        "displaySymbol": "vai",
        "name": "Vai",
        "slug": "vai-vai",
        "logo": "https://assets.coingecko.com/coins/images/13861/large/VAI_logo.png?1696513607",
        "temporaryDataDelay": False,
        "price": 1.001,
        "percentage": 0.001154330943577905,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0011529999999999596,
        "marketCap": 4894291,
        "volume": 47136,
        "FullCount": None,
        "rank": 1636,
        "Status": "active",
    },
    {
        "symbol": "silk-bcec1136-561c-4706-a42c-8b67d0d7f7d2",
        "displaySymbol": "silk",
        "name": "Silk",
        "slug": "silk-silk",
        "logo": "https://assets.coingecko.com/coins/images/30033/large/silk-icon.png?1696528956",
        "temporaryDataDelay": False,
        "price": 1.1,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 4168657,
        "volume": 1186382,
        "FullCount": None,
        "rank": 1716,
        "Status": "active",
    },
    {
        "symbol": "djed",
        "displaySymbol": "djed",
        "name": "Djed",
        "slug": "djed-djed",
        "logo": "https://assets.coingecko.com/coins/images/28650/large/256_Djed__No_Background_%284%29_%283%29.png?1696527635",
        "temporaryDataDelay": False,
        "price": 0.991805,
        "percentage": -0.0019850783189746075,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0019500000000000073,
        "marketCap": 3985799,
        "volume": 107148,
        "FullCount": None,
        "rank": 1745,
        "Status": "active",
    },
    {
        "symbol": "musd",
        "displaySymbol": "musd",
        "name": "mStable USD",
        "slug": "mstable-usd-musd",
        "logo": "https://assets.coingecko.com/coins/images/11576/large/mStable_USD.png?1696511474",
        "temporaryDataDelay": False,
        "price": 1.055,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.000032030460968301836,
        "changeValue": 0,
        "marketCap": 3414241,
        "volume": 329.51,
        "FullCount": None,
        "rank": 1829,
        "Status": "active",
    },
    {
        "symbol": "dola-usd",
        "displaySymbol": "dola",
        "name": "DOLA",
        "slug": "dola-dola",
        "logo": "https://assets.coingecko.com/coins/images/14287/large/dola.png?1696513984",
        "temporaryDataDelay": False,
        "price": 0.995676,
        "percentage": -0.00044231823676056463,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.00043400000000004546,
        "marketCap": 3247226,
        "volume": 1302642,
        "FullCount": None,
        "rank": 1846,
        "Status": "active",
    },
    {
        "symbol": "seur",
        "displaySymbol": "seur",
        "name": "sEUR",
        "slug": "seur-seur",
        "logo": "https://assets.coingecko.com/coins/images/13637/large/sEUR.png?1696513385",
        "temporaryDataDelay": False,
        "price": 1.44,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 3180568,
        "volume": 7848.27,
        "FullCount": None,
        "rank": 1861,
        "Status": "active",
    },
    {
        "symbol": "cnh-tether",
        "displaySymbol": "cnht",
        "name": "CNH Tether",
        "slug": "cnh-tether-cnht",
        "logo": "https://assets.coingecko.com/coins/images/5251/large/cny-tether-logo.png?1696505755",
        "temporaryDataDelay": False,
        "price": 0.13807,
        "percentage": 0.0008247392583185683,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.00011300000000000199,
        "marketCap": 2864011,
        "volume": 315.63,
        "FullCount": None,
        "rank": 1912,
        "Status": "active",
    },
    {
        "symbol": "vnx-euro",
        "displaySymbol": "veur",
        "name": "VNX EURO",
        "slug": "vnx-euro-veur",
        "logo": "https://assets.coingecko.com/coins/images/29351/large/VNXEUR_%281%29.png?1696528300",
        "temporaryDataDelay": False,
        "price": 1.079,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 2334219,
        "volume": 97928,
        "FullCount": None,
        "rank": 2026,
        "Status": "active",
    },
    {
        "symbol": "par-stablecoin",
        "displaySymbol": "par",
        "name": "Parallel",
        "slug": "parallel-par",
        "logo": "https://assets.coingecko.com/coins/images/14153/large/par_round_200.png?1696513872",
        "temporaryDataDelay": False,
        "price": 1.041,
        "percentage": -0.0009451795841210887,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.001000000000000112,
        "marketCap": 2330594,
        "volume": 617.77,
        "FullCount": None,
        "rank": 2028,
        "Status": "active",
    },
    {
        "symbol": "sperax-usd",
        "displaySymbol": "usds",
        "name": "Sperax USD",
        "slug": "sperax-usd-usds",
        "logo": "https://assets.coingecko.com/coins/images/21973/large/USDs_logo_1000X1000.png?1696521321",
        "temporaryDataDelay": False,
        "price": 0.999568,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.002179415779854827,
        "changeValue": 0,
        "marketCap": 1135645,
        "volume": 74677,
        "FullCount": None,
        "rank": 2402,
        "Status": "active",
    },
    {
        "symbol": "spiceusd",
        "displaySymbol": "usds",
        "name": "SpiceUSD",
        "slug": "spiceusd-usds",
        "logo": "https://assets.coingecko.com/coins/images/25697/large/USDS.png?1696524824",
        "temporaryDataDelay": False,
        "price": 0.095478,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 793899,
        "volume": 80.25,
        "FullCount": None,
        "rank": 2570,
        "Status": "active",
    },
    {
        "symbol": "zasset-zusd",
        "displaySymbol": "zusd",
        "name": "Zasset zUSD",
        "slug": "zasset-zusd-zusd",
        "logo": "https://assets.coingecko.com/coins/images/17664/large/zUSD_200x200.png?1699583794",
        "temporaryDataDelay": False,
        "price": 0.996027,
        "percentage": -0.0021642717401347553,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.002155000000000018,
        "marketCap": 583980,
        "volume": 839.16,
        "FullCount": None,
        "rank": 2725,
        "Status": "active",
    },
    {
        "symbol": "straitsx-indonesia-rupiah",
        "displaySymbol": "xidr",
        "name": "XIDR",
        "slug": "xidr-xidr",
        "logo": "https://assets.coingecko.com/coins/images/21126/large/XIDR_Logo_256_X_256.png?1696520505",
        "temporaryDataDelay": False,
        "price": 0.00006413,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0007912644405760598,
        "changeValue": 0,
        "marketCap": 485451,
        "volume": 208439,
        "FullCount": None,
        "rank": 2808,
        "Status": "active",
    },
    {
        "symbol": "usdk",
        "displaySymbol": "usdk",
        "name": "USDK",
        "slug": "usdk-usdk",
        "logo": "https://assets.coingecko.com/coins/images/8824/large/usdk.png?1696508977",
        "temporaryDataDelay": False,
        "price": 0.917999,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0029989315184111138,
        "changeValue": 0,
        "marketCap": 449051,
        "volume": 733.93,
        "FullCount": None,
        "rank": 2840,
        "Status": "active",
    },
    {
        "symbol": "vesta-stable",
        "displaySymbol": "vst",
        "name": "Vesta Stable",
        "slug": "vesta-stable-vst",
        "logo": "https://assets.coingecko.com/coins/images/23621/large/vesta.png?1696522826",
        "temporaryDataDelay": False,
        "price": 0.999182,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 379946,
        "volume": 962.24,
        "FullCount": None,
        "rank": 2918,
        "Status": "active",
    },
    {
        "symbol": "bob",
        "displaySymbol": "bob",
        "name": "BOB",
        "slug": "bob-bob",
        "logo": "https://assets.coingecko.com/coins/images/27266/large/Bob-logo.png?1696526318",
        "temporaryDataDelay": False,
        "price": 0.999564,
        "percentage": 0.0008063568636232618,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0008029999999999982,
        "marketCap": 341954,
        "volume": 10114.08,
        "FullCount": None,
        "rank": 2970,
        "Status": "active",
    },
    {
        "symbol": "basis-cash",
        "displaySymbol": "bac",
        "name": "Basis Cash",
        "slug": "basis-cash-bac",
        "logo": "https://assets.coingecko.com/coins/images/13246/large/BAC.png?1696513021",
        "temporaryDataDelay": False,
        "price": 0.00441553,
        "percentage": -0.0002638846551073169,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0000011600000000000499,
        "marketCap": 241181,
        "volume": 92842,
        "FullCount": None,
        "rank": 3114,
        "Status": "active",
    },
    {
        "symbol": "convertible-jpy-token",
        "displaySymbol": "cjpy",
        "name": "Convertible JPY Token",
        "slug": "convertible-jpy-token-cjpy",
        "logo": "https://assets.coingecko.com/coins/images/31356/large/CJPY_logo.png?1696530173",
        "temporaryDataDelay": False,
        "price": 0.00701055,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.00003347644513623735,
        "changeValue": 0,
        "marketCap": 222379,
        "volume": 15331.04,
        "FullCount": None,
        "rank": 3155,
        "Status": "active",
    },
    {
        "symbol": "one-cash",
        "displaySymbol": "onc",
        "name": "One Cash",
        "slug": "one-cash-onc",
        "logo": "https://assets.coingecko.com/coins/images/13529/large/onc_logo.png?1696513290",
        "temporaryDataDelay": False,
        "price": 0.115713,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 176475,
        "volume": 30384,
        "FullCount": None,
        "rank": 3255,
        "Status": "active",
    },
    {
        "symbol": "poundtoken",
        "displaySymbol": "gbpt",
        "name": "poundtoken",
        "slug": "poundtoken-gbpt",
        "logo": "https://assets.coingecko.com/coins/images/26591/large/gbpt.jpeg?1696525666",
        "temporaryDataDelay": False,
        "price": 1.24,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 136239,
        "volume": 49856,
        "FullCount": None,
        "rank": 3344,
        "Status": "active",
    },
    {
        "symbol": "coin98-dollar",
        "displaySymbol": "cusd",
        "name": "Coin98 Dollar",
        "slug": "coin98-dollar-cusd",
        "logo": "https://assets.coingecko.com/coins/images/26588/large/CUSD-01.png?1696525663",
        "temporaryDataDelay": False,
        "price": 0.998314,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0029980798943424155,
        "changeValue": 0,
        "marketCap": 46574,
        "volume": 44.66,
        "FullCount": None,
        "rank": 3604,
        "Status": "active",
    },
    {
        "symbol": "usd-balance",
        "displaySymbol": "usdb",
        "name": "USD Balance",
        "slug": "usd-balance-usdb",
        "logo": "https://assets.coingecko.com/coins/images/24341/large/usdb.png?1696523525",
        "temporaryDataDelay": False,
        "price": 0.04370914,
        "percentage": 0.002987463744212585,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.00011366000000000154,
        "marketCap": 8469.9,
        "volume": 12.66,
        "FullCount": None,
        "rank": 3770,
        "Status": "active",
    },
    {
        "symbol": "iron-stablecoin",
        "displaySymbol": "iron",
        "name": "Iron",
        "slug": "iron-iron",
        "logo": "https://assets.coingecko.com/coins/images/14588/large/logo_-_2021-03-31T123525.615.png?1696514268",
        "temporaryDataDelay": False,
        "price": 0.00029368,
        "percentage": 0.000980191954257644,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 2.3999999999998415e-7,
        "marketCap": 0,
        "volume": 148.66,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "wrapped-ust",
        "displaySymbol": "ustc",
        "name": "Wrapped USTC",
        "slug": "wrapped-ustc-ustc",
        "logo": "https://assets.coingecko.com/coins/images/15462/large/ust.png?1696515108",
        "temporaryDataDelay": False,
        "price": 0.0327745,
        "percentage": 0.003136750878393643,
        "percentage_1h": None,
        "percentage_7d": -0.00028472731411341196,
        "changeValue": 0.00007882999999999848,
        "marketCap": 0,
        "volume": 37602,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "xdollar-stablecoin",
        "displaySymbol": "xusd",
        "name": "xDollar Stablecoin",
        "slug": "xdollar-stablecoin-xusd",
        "logo": "https://assets.coingecko.com/coins/images/16291/large/xUSD-web-transparent.png?1696515890",
        "temporaryDataDelay": False,
        "price": 1.054,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.001910219675262657,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 22.54,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "jpy-coin",
        "displaySymbol": "jpyc",
        "name": "JPY Coin",
        "slug": "jpy-coin-jpyc",
        "logo": "https://assets.coingecko.com/coins/images/25971/large/2023jpyc.png?1696525049",
        "temporaryDataDelay": False,
        "price": 0.00664848,
        "percentage": -0.0010460043397727628,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.000006850000000000085,
        "marketCap": 0,
        "volume": 38477,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "monerium-eur-money",
        "displaySymbol": "eure",
        "name": "Monerium EUR emoney",
        "slug": "monerium-eur-emoney-eure",
        "logo": "https://assets.coingecko.com/coins/images/23354/large/eur.png?1696522569",
        "temporaryDataDelay": False,
        "price": 1.079,
        "percentage": -0.0018604651162790714,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.0020000000000000018,
        "marketCap": 0,
        "volume": 100708,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "iron-bsc",
        "displaySymbol": "iron",
        "name": "Iron BSC",
        "slug": "iron-bsc-iron",
        "logo": "https://assets.coingecko.com/coins/images/16409/large/qBa5_yCL_400x400.jpg?1696516006",
        "temporaryDataDelay": False,
        "price": 0.01003146,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 0.666538,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "jarvis-synthetic-swiss-franc",
        "displaySymbol": "jchf",
        "name": "Jarvis Synthetic Swiss Franc",
        "slug": "jarvis-synthetic-swiss-franc-jchf",
        "logo": "https://assets.coingecko.com/coins/images/15727/large/jCHF.png?1696515353",
        "temporaryDataDelay": False,
        "price": 1.13,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 656.41,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "jarvis-synthetic-euro",
        "displaySymbol": "jeur",
        "name": "Jarvis Synthetic Euro",
        "slug": "jarvis-synthetic-euro-jeur",
        "logo": "https://assets.coingecko.com/coins/images/15725/large/jEUR.png?1696515352",
        "temporaryDataDelay": False,
        "price": 1.044,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 7413.69,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "xdai",
        "displaySymbol": "xdai",
        "name": "XDAI",
        "slug": "xdai-xdai",
        "logo": "https://assets.coingecko.com/coins/images/11062/large/Identity-Primary-DarkBG.png?1696511004",
        "temporaryDataDelay": False,
        "price": 1.006,
        "percentage": 0.000781610437751916,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.0007810000000000317,
        "marketCap": 0,
        "volume": 168782,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "bridged-usdc-polygon-pos-bridge",
        "displaySymbol": "usdc.e",
        "name": "Bridged USDC (Polygon PoS Bridge)",
        "slug": "bridged-usdc-(polygon-pos-bridge)-usdc.e",
        "logo": "https://assets.coingecko.com/coins/images/33000/large/usdc.png?1700119918",
        "temporaryDataDelay": False,
        "price": 1,
        "percentage": -0.0009980039920160797,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": -0.001000000000000112,
        "marketCap": 0,
        "volume": 37772641,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "decentralized-usd",
        "displaySymbol": "dusd",
        "name": "Decentralized USD",
        "slug": "decentralized-usd-dusd",
        "logo": "https://assets.coingecko.com/coins/images/24343/large/Untitled_%285_%C3%97_3_cm%29_%282%29.png?1696523527",
        "temporaryDataDelay": False,
        "price": 0.251487,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0023837635371711944,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 38319,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "utopia-usd",
        "displaySymbol": "uusd",
        "name": "Utopia USD",
        "slug": "utopia-usd-uusd",
        "logo": "https://assets.coingecko.com/coins/images/28253/large/uusd-flat-500.png?1696527255",
        "temporaryDataDelay": False,
        "price": 0.999508,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 48265,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "binance-peg-busd",
        "displaySymbol": "busd",
        "name": "Binance-Peg BUSD",
        "slug": "binance-peg-busd-busd",
        "logo": "https://assets.coingecko.com/coins/images/31273/large/new_binance-peg-busd.png?1696530096",
        "temporaryDataDelay": False,
        "price": 1.003,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 9354542,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "sora-synthetic-usd",
        "displaySymbol": "xstusd",
        "name": "SORA Synthetic USD",
        "slug": "sora-synthetic-usd-xstusd",
        "logo": "https://assets.coingecko.com/coins/images/21601/large/15731.png?1696520962",
        "temporaryDataDelay": False,
        "price": 0.722018,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0.0006094128957245476,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 4303.37,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "klaytn-dai",
        "displaySymbol": "kdai",
        "name": "Klaytn Dai",
        "slug": "klaytn-dai-kdai",
        "logo": "https://assets.coingecko.com/coins/images/27010/large/download_%284%29.png?1696526062",
        "temporaryDataDelay": False,
        "price": 0.442023,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": -0.0009424068487124428,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 11077.18,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "bdollar",
        "displaySymbol": "bdo",
        "name": "bDollar",
        "slug": "bdollar-bdo",
        "logo": "https://assets.coingecko.com/coins/images/13487/large/bdollar-yellow.png?1696513248",
        "temporaryDataDelay": False,
        "price": 0.01983558,
        "percentage": 0,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0,
        "marketCap": 0,
        "volume": 13.58,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
    {
        "symbol": "jpyc",
        "displaySymbol": "jpyc",
        "name": "JPY Coin v1",
        "slug": "jpy-coin-v1-jpyc",
        "logo": "https://assets.coingecko.com/coins/images/17277/large/WoZ8rruL_400x400.png?1696516831",
        "temporaryDataDelay": False,
        "price": 0.00694815,
        "percentage": 0.000984117936918181,
        "percentage_1h": None,
        "percentage_7d": 0,
        "changeValue": 0.000007010000000000002,
        "marketCap": 0,
        "volume": 507.16,
        "FullCount": None,
        "rank": None,
        "Status": "active",
    },
]

all_names = list()
for i in response:
    all_names.append(i["name"])

newlist = sorted(all_names)
with open("stablecoin-resp.json", "w") as file:
    file.write(json.dumps(newlist))


unique_names = list()
for name in names:
    if name in newlist:
        unique_names.append(name)

with open("unique_names-stablecoin-resp.json", "w") as file:
    file.write(json.dumps(unique_names))
