import json

stable_coins = [
    "Alchemix USD",
    "BOB",
    "BUSD",
    "Basis Cash",
    "Bean",
    "BiLira",
    "Binance-Peg BUSD",
    "Bridged USDC (Polygon PoS Bridge)",
    "CNH Tether",
    "Celo Dollar",
    "Celo Euro",
    "Coin98 Dollar",
    "Convertible JPY Token",
    "DOLA",
    "Dai",
    "Decentralized USD",
    "Djed",
    "Ethena USDe",
    "Euro Tether",
    "Fei USD",
    "First Digital USD",
    "Frax",
    "GHO",
    "GYEN",
    "Gemini Dollar",
    "HUSD",
    "Iron",
    "Iron BSC",
    "JPY Coin",
    "JPY Coin v1",
    "Jarvis Synthetic Euro",
    "Jarvis Synthetic Swiss Franc",
    "Klaytn Dai",
    "Liquity USD",
    "Lista USD",
    "MAI",
    "Magic Internet Money",
    "Monerium EUR emoney",
    "One Cash",
    "Origin Dollar",
    "PAX Gold",
    "Parallel",
    "Pax Dollar",
    "PayPal USD",
    "Prisma mkUSD",
    "SORA Synthetic USD",
    "STASIS EURO",
    "Silk",
    "Sperax USD",
    "SpiceUSD",
    "TOR",
    "TerraClassicUSD",
    "Tether",
    "Tether Gold",
    "TrueUSD",
    "USD Balance",
    "USDC",
    "USDD",
    "USDK",
    "USDX",
    "USK",
    "Utopia USD",
    "VNX EURO",
    "Vai",
    "Verified USD",
    "Vesta Stable",
    "Wrapped USTC",
    "XDAI",
    "XIDR",
    "XSGD",
    "ZUSD",
    "Zasset zUSD",
    "agEUR",
    "bDollar",
    "crvUSD",
    "dForce USD",
    "eUSD",
    "flexUSD",
    "mStable USD",
    "poundtoken",
    "sEUR",
    "sUSD",
    "xDollar Stablecoin",
]

all_tokens = [
 "A16Z",
 "Aave",
 "Algorand",
 "ApeCoin",
 "Aptos",
 "Arbitrum",
 "Artificial Intelligence",
 "Astar",
 "Avalanche",
 "Axie Infinity",
 "BNB",
 "Binance",
 "Binance USD",
 "BitTorrent",
 "Bitcoin",
 "Bitcoin Cash",
 "Bitcoin ETF",
 "Bitcoin Halving",
 "Bitcoin Mining",
 "Bitcoin SV",
 "Bittensor",
 "BlackRock",
 "BlockFi",
 "Blockchain",
 "Blockstream",
 "Blur",
 "Bonk",
 "CBDC",
 "Cardano",
 "Celestia",
 "Chainlink",
 "Circle",
 "Coinbase",
 "Cosmos",
 "Cosmos Hub",
 "Cronos",
 "Crypto ETF",
 "Crypto Gaming",
 "Crypto Governance",
 "Crypto Mining",
 "Crypto Regulation",
 "Crypto Taxes",
 "Crypto Wallet",
 "DAO",
 "Dai",
 "DeFi",
 "Decentraland",
 "Digital Currency Group",
 "Digital Wallet",
 "Dogecoin",
 "Dragonfly",
 "EOS",
 "Ethereum",
 "Ethereum Classic",
 "FTX",
 "Fantom",
 "Filecoin",
 "First Digital USD",
 "Flow",
 "GALA",
 "Gemini",
 "Goldman Sachs",
 "Grayscale",
 "HSBC",
 "Hedera",
 "Helium",
 "IBM",
 "IMF",
 "IOTA",
 "Immutable",
 "Injective",
 "Internet Computer",
 "JPMorgan",
 "Kaspa",
 "Kava",
 "Kraken",
 "KuCoin",
 "LEO Token",
 "Lido DAO",
 "Lido Staked Ether",
 "Litecoin",
 "Maker",
 "Mantle",
 "Marathon",
 "Microsoft",
 "Mina Protocol",
 "Miners",
 "Monero",
 "Multicoin",
 "MultiversX",
 "NEAR Protocol",
 "NEO",
 "NFT",
 "OKB",
 "ORDI",
 "Optimism",
 "Osmosis",
 "PancakeSwap",
 "Pantera",
 "PayPal",
 "Polkadot",
 "Polychain",
 "Polygon",
 "Quant",
 "Regulation",
 "Render",
 "Riot",
 "Robinhood",
 "Rocket Pool ETH",
 "SATS (Ordinals)",
 "Santander",
 "Sei",
 "Sequoia",
 "Seven Seven Six",
 "Shiba Inu",
 "Solana",
 "Stablecoins",
 "Stacks",
 "Stellar",
 "Stronghold Digital",
 "Sui",
 "Synthetix Network",
 "THORChain",
 "TRON",
 "Tether",
 "Tezos",
 "The Graph",
 "The Sandbox",
 "Theta Network",
 "Tokenize Xchange",
 "Toncoin",
 "TrueUSD",
 "USDC",
 "USDT",
 "Union Square Ventures",
 "Uniswap",
 "VeChain",
 "WOO",
 "Web3",
 "WhiteBIT Coin",
 "Wrapped Bitcoin",
 "XRP",
 "dYdX"
 ]

result = list()
for item in stable_coins:
    if item in all_tokens:
        result.append(item)

sorted_stable_tokens = sorted(result)
with open("stable_token.json", "w") as file:
    file.write(json.dumps(sorted_stable_tokens))