import json


d = [
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Aave",
        "NewsPageMetaTitle": "Aave (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Aave news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Aave News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Algorand",
        "NewsPageMetaTitle": "Algorand (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Algorand news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Algorand News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Aptos",
        "NewsPageMetaTitle": "Aptos (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Aptos news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Aptos News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Arbitrum",
        "NewsPageMetaTitle": "Arbitrum (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Arbitrum news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Arbitrum News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Astar",
        "NewsPageMetaTitle": "Astar (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Astar news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Astar News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Avalanche",
        "NewsPageMetaTitle": "Avalanche (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Avalanche news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Avalanche News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Axie Infinity",
        "NewsPageMetaTitle": "Axie Infinity (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Axie Infinity news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Axie Infinity News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "BNB",
        "NewsPageMetaTitle": "BNB (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest BNB news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest BNB News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "BitTorrent",
        "NewsPageMetaTitle": "BitTorrent (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking BitTorrent news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest BitTorrent News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin",
        "NewsPageMetaTitle": "Bitcoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bitcoin news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bitcoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin Cash",
        "NewsPageMetaTitle": "Bitcoin Cash (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Bitcoin Cash news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Bitcoin Cash News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Bitcoin Cash",
        "NewsPageMetaTitle": "Bitcoin Cash News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Bitcoin Cash news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Bitcoin Cash News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Bitcoin ETF",
        "NewsPageMetaTitle": "Bitcoin ETF News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bitcoin ETF news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bitcoin ETF News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Bitcoin Halving",
        "NewsPageMetaTitle": "Bitcoin Halving News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Bitcoin Halving news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Bitcoin Halving News",
    },
    {
        "Category": "Miners",
        "NewsTag": "Bitcoin Mining",
        "NewsPageMetaTitle": "Bitcoin Mining News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bitcoin Mining news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bitcoin Mining News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bitcoin SV",
        "NewsPageMetaTitle": "Bitcoin SV (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Bitcoin SV News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bittensor",
        "NewsPageMetaTitle": "Bittensor (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Bittensor news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Bittensor News",
    },
    {
        "Category": "Enterprise Blockchain",
        "NewsTag": "BlackRock",
        "NewsPageMetaTitle": "BlackRock News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "  Stay informed with the latest BlackRock news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest BlackRock News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Blockchain",
        "NewsPageMetaTitle": "Blockchain News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Blockchain news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Blockchain News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Blur",
        "NewsPageMetaTitle": "Blur (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Blur news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Blur News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Bonk",
        "NewsPageMetaTitle": "Bonk (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Bonk news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Bonk News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "CBDC",
        "NewsPageMetaTitle": "CBDC (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking CBDC news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest CBDC News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cardano",
        "NewsPageMetaTitle": "Cardano (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Cardano news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Cardano News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Celestia",
        "NewsPageMetaTitle": "Celestia (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Celestia News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Chainlink",
        "NewsPageMetaTitle": "Chainlink (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Chainlink news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Chainlink News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cosmos Hub",
        "NewsPageMetaTitle": "Cosmos Hub (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Cosmos Hub News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Cronos",
        "NewsPageMetaTitle": "Cronos (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Cronos news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Cronos News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto ETF",
        "NewsPageMetaTitle": "Crypto ETF News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Crypto ETF news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Crypto ETF News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto Gaming",
        "NewsPageMetaTitle": "Crypto Gaming News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Crypto Gaming news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Crypto Gaming News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto Governance",
        "NewsPageMetaTitle": "Crypto Governance News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Crypto Governance news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Crypto Governance News",
    },
    {
        "Category": "Miners",
        "NewsTag": "Crypto Mining",
        "NewsPageMetaTitle": "Crypto Mining News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Crypto Mining news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Crypto Mining News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto Regulation",
        "NewsPageMetaTitle": "Crypto Regulation News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Crypto Regulation news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Crypto Regulation News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto Taxes",
        "NewsPageMetaTitle": "Crypto Taxes News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Crypto Taxes news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Crypto Taxes News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Crypto Wallet",
        "NewsPageMetaTitle": "Crypto Wallet News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Crypto Wallet news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Crypto Wallet News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "DAO",
        "NewsPageMetaTitle": "DAO (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with DAO news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest DAO News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Dai",
        "NewsPageMetaTitle": "Dai (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Dai news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Dai News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "DeFi",
        "NewsPageMetaTitle": "DeFi (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest DeFi news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest DeFi News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Decentraland",
        "NewsPageMetaTitle": "Decentraland (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Decentraland news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Decentraland News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Digital Wallet",
        "NewsPageMetaTitle": "Digital Wallet News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Digital Wallet News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Dogecoin",
        "NewsPageMetaTitle": "Dogecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Dogecoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Dogecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "EOS",
        "NewsPageMetaTitle": "EOS (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest EOS news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest EOS News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Ethereum",
        "NewsPageMetaTitle": "Ethereum (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Ethereum news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Ethereum News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Ethereum Classic",
        "NewsPageMetaTitle": "Ethereum Classic (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Ethereum Classic news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Ethereum Classic News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Fantom",
        "NewsPageMetaTitle": "Fantom (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Fantom News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Filecoin",
        "NewsPageMetaTitle": "Filecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Filecoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Filecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "First Digital USD",
        "NewsPageMetaTitle": "First Digital USD (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking First Digital USD news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest First Digital USD News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Flow",
        "NewsPageMetaTitle": "Flow (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Flow news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Flow News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "GALA",
        "NewsPageMetaTitle": "GALA (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with GALA news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest GALA News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Grayscale",
        "NewsPageMetaTitle": "Grayscale News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Grayscale news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Grayscale News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Hedera",
        "NewsPageMetaTitle": "Hedera (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Hedera News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Helium",
        "NewsPageMetaTitle": "Helium (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Helium news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Helium News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "IOTA",
        "NewsPageMetaTitle": "IOTA (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest IOTA news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest IOTA News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Immutable",
        "NewsPageMetaTitle": "Immutable (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Immutable news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Immutable News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Injective",
        "NewsPageMetaTitle": "Injective (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Injective news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Injective News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Internet Computer",
        "NewsPageMetaTitle": "Internet Computer (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Internet Computer news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Internet Computer News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Kaspa",
        "NewsPageMetaTitle": "Kaspa (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Kaspa news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Kaspa News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Kava",
        "NewsPageMetaTitle": "Kava (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Kava news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Kava News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "KuCoin",
        "NewsPageMetaTitle": "KuCoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking KuCoin news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest KuCoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "LEO Token",
        "NewsPageMetaTitle": "LEO Token (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking LEO Token news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest LEO Token News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Lido DAO",
        "NewsPageMetaTitle": "Lido DAO (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Lido DAO news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Lido DAO News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Lido Staked Ether",
        "NewsPageMetaTitle": "Lido Staked Ether (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Lido Staked Ether news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Lido Staked Ether News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Litecoin",
        "NewsPageMetaTitle": "Litecoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Litecoin news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Litecoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Maker",
        "NewsPageMetaTitle": "Maker (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Maker news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Maker News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Mantle",
        "NewsPageMetaTitle": "Mantle (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Mantle news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Mantle News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Mina Protocol",
        "NewsPageMetaTitle": "Mina Protocol (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Mina Protocol news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Mina Protocol News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Monero",
        "NewsPageMetaTitle": "Monero (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Monero news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Monero News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "MultiversX",
        "NewsPageMetaTitle": "MultiversX (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest MultiversX News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "NEAR Protocol",
        "NewsPageMetaTitle": "NEAR Protocol (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking NEAR Protocol news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest NEAR Protocol News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "NEO",
        "NewsPageMetaTitle": "NEO (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in NEO news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest NEO News",
    },
    {
        "Category": "Industry",
        "NewsTag": "NFT",
        "NewsPageMetaTitle": "NFT News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking NFT news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest NFT News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "OKB",
        "NewsPageMetaTitle": "OKB (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in OKB news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest OKB News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "ORDI",
        "NewsPageMetaTitle": "ORDI (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in ORDI news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest ORDI News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Optimism",
        "NewsPageMetaTitle": "Optimism (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Optimism news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Optimism News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Osmosis",
        "NewsPageMetaTitle": "Osmosis (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Osmosis news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Osmosis News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "PancakeSwap",
        "NewsPageMetaTitle": "PancakeSwap (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking PancakeSwap news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest PancakeSwap News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Polkadot",
        "NewsPageMetaTitle": "Polkadot (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Polkadot news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Polkadot News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Polygon",
        "NewsPageMetaTitle": "Polygon (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Polygon news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Polygon News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Quant",
        "NewsPageMetaTitle": "Quant (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Quant news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Quant News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Render",
        "NewsPageMetaTitle": "Render (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Render news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Render News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Rocket Pool ETH",
        "NewsPageMetaTitle": "Rocket Pool ETH (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Rocket Pool ETH news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Rocket Pool ETH News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "SATS (Ordinals)",
        "NewsPageMetaTitle": "SATS (Ordinals) (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking SATS (Ordinals) news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest SATS (Ordinals) News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Sei",
        "NewsPageMetaTitle": "Sei (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Sei news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Sei News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Shiba Inu",
        "NewsPageMetaTitle": "Shiba Inu (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Shiba Inu news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Shiba Inu News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Solana",
        "NewsPageMetaTitle": "Solana (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Solana news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Solana News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Stacks",
        "NewsPageMetaTitle": "Stacks (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Stacks news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Stacks News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Stellar",
        "NewsPageMetaTitle": "Stellar (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Stellar news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Stellar News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Sui",
        "NewsPageMetaTitle": "Sui (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Sui news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Sui News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Synthetix Network",
        "NewsPageMetaTitle": "Synthetix Network (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Synthetix Network news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest Synthetix Network News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "THORChain",
        "NewsPageMetaTitle": "THORChain (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest THORChain news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest THORChain News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "TRON",
        "NewsPageMetaTitle": "TRON (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in TRON news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest TRON News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Tether",
        "NewsPageMetaTitle": "Tether (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Tether news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Tether News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Tezos",
        "NewsPageMetaTitle": "Tezos (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Tezos news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Tezos News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "The Graph",
        "NewsPageMetaTitle": "The Graph (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking The Graph news on Forbes. From price movements to regulatory shifts, we provide insights for crypto enthusiasts. Stay ahead in the crypto game!",
        "NewsPageH1": "Latest The Graph News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "The Sandbox",
        "NewsPageMetaTitle": "The Sandbox (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest The Sandbox news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest The Sandbox News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Theta Network",
        "NewsPageMetaTitle": "Theta Network (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest Theta Network news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest Theta Network News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Tokenize Xchange",
        "NewsPageMetaTitle": "Tokenize Xchange (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Tokenize Xchange News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Toncoin",
        "NewsPageMetaTitle": "Toncoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in Toncoin news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest Toncoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "TrueUSD",
        "NewsPageMetaTitle": "TrueUSD (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest TrueUSD news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest TrueUSD News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "USDC",
        "NewsPageMetaTitle": "USDC (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with USDC news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest USDC News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Uniswap",
        "NewsPageMetaTitle": "Uniswap (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with Uniswap news and market trends with Forbes. From price fluctuations to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Uniswap News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "VeChain",
        "NewsPageMetaTitle": "VeChain (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in VeChain news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest VeChain News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "WOO",
        "NewsPageMetaTitle": "WOO (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest WOO news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest WOO News",
    },
    {
        "Category": "Industry",
        "NewsTag": "Web3",
        "NewsPageMetaTitle": "Web3 News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Explore breaking Web3 news on Forbes. From new innovations to regulatory shifts, we provide insights for Web3 enthusiasts. Stay ahead in the Web3 game!",
        "NewsPageH1": "Latest Web3 News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "WhiteBIT Coin",
        "NewsPageMetaTitle": "WhiteBIT Coin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest WhiteBIT Coin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "Wrapped Bitcoin",
        "NewsPageMetaTitle": "Wrapped Bitcoin (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Keep up with digital wallet news and trends with Forbes. From new wallet uses to industry advancements, we keep you in the loop with timely updates.",
        "NewsPageH1": "Latest Wrapped Bitcoin News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "XRP",
        "NewsPageMetaTitle": "XRP (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Unlock the latest in XRP news trends and developments on Forbes. Instant updates and market analysis to keep you informed and engaged in the crypto space.",
        "NewsPageH1": "Latest XRP News",
    },
    {
        "Category": "Protocol Tokens",
        "NewsTag": "dYdX",
        "NewsPageMetaTitle": "dYdX (Ticker) News: Today's Latest Stories By Forbes",
        "NewsPageMetaDescription": "Stay informed with the latest dYdX news! Our page delivers real-time updates, expert analyses, and market trends. Dive into the world of crypto today!",
        "NewsPageH1": "Latest dYdX News",
    },
]

d2 = [
    {
        "topicName": "A16Z",
        "bertieTag": "A16Z",
        "forbesMetaDataDescription": "Keep up with the latest A16Z news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "a16z",
        "topicUrl": "/news/a16z",
        "topicOrder": 1,
        "titleTemplate": "Latest A16Z News | Forbes Digital Assets",
        "description": "Uncover the latest A16Z news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "A16Z News",
        "aliasesName": "A16Z",
        "articles": None,
    },
    {
        "topicName": "Algorand",
        "bertieTag": "Algorand",
        "forbesMetaDataDescription": "Discover the latest Algorand news, analysis, and trends to stay ahead of the game. Find the latest ALGO articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "algorand-algo",
        "topicUrl": "/assets/algorand-algo",
        "topicOrder": 2,
        "titleTemplate": "Latest Algorand (ALGO) News | Forbes Digital Assets",
        "description": "Unlock the world of Algorand with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Algorand News",
        "aliasesName": "Algorand",
        "articles": None,
    },
    {
        "topicName": "ApeCoin",
        "bertieTag": "ApeCoin",
        "forbesMetaDataDescription": "Discover the latest ApeCoin news, analysis, and trends to stay ahead of the game. Find the latest APE articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "apecoin-ape",
        "topicUrl": "/assets/apecoin-ape",
        "topicOrder": 3,
        "titleTemplate": "Latest ApeCoin (APE) News | Forbes Digital Assets",
        "description": "Unlock the world of ApeCoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "ApeCoin News",
        "aliasesName": "ApeCoin",
        "articles": None,
    },
    {
        "topicName": "Aptos",
        "bertieTag": "Aptos",
        "forbesMetaDataDescription": "Discover the latest Aptos news, analysis, and trends to stay ahead of the game. Find the latest APT articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "aptos-apt",
        "topicUrl": "/assets/aptos-apt",
        "topicOrder": 4,
        "titleTemplate": "Latest Aptos (APT) News | Forbes Digital Assets",
        "description": "Unlock the world of Aptos with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Aptos News",
        "aliasesName": "Aptos",
        "articles": None,
    },
    {
        "topicName": "Artificial Intelligence",
        "bertieTag": "Artificial Intelligence",
        "forbesMetaDataDescription": "Keep up with the latest AI news. Dive into all the updates and expert insights to stay informed on any changes in the world of artificial intelligence. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": True,
        "slug": "artificial-intelligence",
        "topicUrl": "/news/artificial-intelligence",
        "topicOrder": 5,
        "titleTemplate": "Latest Artificial Intelligence News | Forbes Digital Assets",
        "description": "Keep up with the latest on Artificial Intelligence news. Dive into the latest updates to stay informed, maximize opportunities, and drive success in the new AI landscape.",
        "newsHeader": "Artificial Intelligence News",
        "aliasesName": "Artificial Intelligence News",
        "articles": None,
    },
    {
        "topicName": "Avalanche",
        "bertieTag": "Avalanche",
        "forbesMetaDataDescription": "Discover the latest Avalanche news, analysis, and trends to stay ahead of the game. Find the latest AVAX articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "avalanche-avax",
        "topicUrl": "/assets/avalanche-avax",
        "topicOrder": 6,
        "titleTemplate": "Latest Avalanche (AVAX) News | Forbes Digital Assets",
        "description": "Unlock the world of Avalanche with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Avalanche News",
        "aliasesName": "Avalanche",
        "articles": None,
    },
    {
        "topicName": "KuCoin",
        "bertieTag": "KuCoin",
        "forbesMetaDataDescription": "Kucoin Info",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "kucoin-kcs",
        "topicUrl": "/assets/kucoin-kcs",
        "topicOrder": 7,
        "titleTemplate": "Latest KuCoin News | Forbes Digital Assets",
        "description": "KuCoin News",
        "newsHeader": "KuCoin News",
        "aliasesName": "KuCoin",
        "articles": None,
    },
    {
        "topicName": "BNB",
        "bertieTag": "BNB",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge BNB crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "bnb-bnb",
        "topicUrl": "/assets/bnb-bnb",
        "topicOrder": 8,
        "titleTemplate": "Latest BNB News Crypto | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge BNB crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "BNB Crypto News",
        "aliasesName": "BNB",
        "articles": None,
    },
    {
        "topicName": "Binance",
        "bertieTag": "Binance",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Binance news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "binance",
        "topicUrl": "/news/binance",
        "topicOrder": 9,
        "titleTemplate": "Latest Binance News | Forbes Digital Assets",
        "description": "Stay informed on Binance. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Binance News",
        "aliasesName": "Binance",
        "articles": None,
    },
    {
        "topicName": "Binance USD",
        "bertieTag": "Binance USD",
        "forbesMetaDataDescription": "Discover the latest Binance USD news, analysis, and trends to stay ahead of the game. Find the latest BNB articles and important investing insights today.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "binance-usd-busd",
        "topicUrl": "/news/binance-usd-busd",
        "topicOrder": 10,
        "titleTemplate": "Latest Binance USD News | Forbes Digital Assets",
        "description": "Unlock the world of Binance USD with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Binance USD News",
        "aliasesName": "Binance USD",
        "articles": None,
    },
    {
        "topicName": "Bitcoin",
        "bertieTag": "Bitcoin",
        "forbesMetaDataDescription": "Discover the latest Bitcoin news, analysis, and trends to stay ahead of the game. Find the latest BTC articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": True,
        "slug": "bitcoin-btc",
        "topicUrl": "/assets/bitcoin-btc",
        "topicOrder": 11,
        "titleTemplate": "Latest Bitcoin (BTC) News | Forbes Digital Assets",
        "description": "Unlock the world of Bitcoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Bitcoin News",
        "aliasesName": "Bitcoin",
        "articles": None,
    },
    {
        "topicName": "BlockFi",
        "bertieTag": "BlockFi",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our BlockFi news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "blockfi",
        "topicUrl": "/news/blockfi",
        "topicOrder": 12,
        "titleTemplate": "Latest BlockFi News | Forbes Digital Assets",
        "description": "Keep up with the newest on BlockFi. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "BlockFi News",
        "aliasesName": "BlockFi",
        "articles": None,
    },
    {
        "topicName": "Blockstream",
        "bertieTag": "Blockstream",
        "forbesMetaDataDescription": "Stay informed with the latest Blockstream news. Discover real-time updates, news, analysis, and insights on our Blockstream news page.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "blockstream",
        "topicUrl": "/news/blockstream",
        "topicOrder": 13,
        "titleTemplate": "Latest Blockstream News | Forbes Digital Assets",
        "description": "Discover the latest on Blockstream. Keep up with the most recent news, innovations, and other updates to stay informed for crypto success.",
        "newsHeader": "Blockstream News",
        "aliasesName": "Blockstream",
        "articles": None,
    },
    {
        "topicName": "Cardano",
        "bertieTag": "Cardano",
        "forbesMetaDataDescription": "Discover the latest Cardano USD news, analysis, and trends to stay ahead of the game. Find the latest ADA articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "cardano-ada",
        "topicUrl": "/assets/cardano-ada",
        "topicOrder": 14,
        "titleTemplate": "Latest Cardano USD (ADA) News | Forbes Digital Assets",
        "description": "Unlock the world of Cardano with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Cardano News",
        "aliasesName": "Cardano",
        "articles": None,
    },
    {
        "topicName": "Chainlink",
        "bertieTag": "Chainlink",
        "forbesMetaDataDescription": "Discover the latest Chainlink news, analysis, and trends to stay ahead of the game. Find the latest LINK articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "chainlink-link",
        "topicUrl": "/assets/chainlink-link",
        "topicOrder": 15,
        "titleTemplate": "Latest Chainlink (LINK) News | Forbes Digital Assets",
        "description": "Unlock the world of Chainlink with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Chainlink News",
        "aliasesName": "Chainlink",
        "articles": None,
    },
    {
        "topicName": "Circle",
        "bertieTag": "Circle",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Circle news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "circle",
        "topicUrl": "/news/circle",
        "topicOrder": 16,
        "titleTemplate": "Latest Circle News | Forbes Digital Assets",
        "description": "Keep up with the newest on Circle. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Circle News",
        "aliasesName": "Circle",
        "articles": None,
    },
    {
        "topicName": "Coinbase",
        "bertieTag": "Coinbase",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Coinbase news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": True,
        "slug": "coinbase-coin7",
        "topicUrl": "/assets/coinbase-coin7",
        "topicOrder": 17,
        "titleTemplate": "Latest Coinbase News | Forbes Digital Assets",
        "description": "Keep up with the newest on Coinbase. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Coinbase News",
        "aliasesName": "Coinbase",
        "articles": None,
    },
    {
        "topicName": "Cosmos",
        "bertieTag": "Cosmos",
        "forbesMetaDataDescription": "Discover the latest Cosmos news, analysis, and trends to stay ahead of the game. Find the latest ATOM articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "cosmos-hub-atom",
        "topicUrl": "/assets/cosmos-hub-atom",
        "topicOrder": 18,
        "titleTemplate": "Latest Cosmos (ATOM) News | Forbes Digital Assets",
        "description": "Unlock the world of Cosmos with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Cosmos News",
        "aliasesName": "Cosmos Hub",
        "articles": None,
    },
    {
        "topicName": "Crypto Gaming",
        "bertieTag": "Gaming",
        "forbesMetaDataDescription": "Keep up with the latest crypto gaming news. Dive into all the updates and expert insights to stay informed on any changes in the world of crypto gaming. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "gaming",
        "topicUrl": "/news/gaming",
        "topicOrder": 19,
        "titleTemplate": "Latest Crypto Gaming News | Forbes Digital Assets",
        "description": "Unlock the world of Crypto Gaming. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Gaming News",
        "aliasesName": "Gaming",
        "articles": None,
    },
    {
        "topicName": "Dai",
        "bertieTag": "Dai",
        "forbesMetaDataDescription": "Discover the latest Dai news, analysis, and trends to stay ahead of the game. Find the latest DAI articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "dai-dai",
        "topicUrl": "/assets/dai-dai",
        "topicOrder": 20,
        "titleTemplate": "Latest Dai (DAI) News | Forbes Digital Assets",
        "description": "Unlock the world of Dai with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Dai News",
        "aliasesName": "Dai",
        "articles": None,
    },
    {
        "topicName": "Digital Currency Group",
        "bertieTag": "Digital Currency Group",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Digital Currency Group news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "digital-currency-group",
        "topicUrl": "/news/digital-currency-group",
        "topicOrder": 21,
        "titleTemplate": "Latest Digital Currency Group News | Forbes Digital Assets",
        "description": "Keep up with the newest on Digital Currency Group. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Digital Currency Group News",
        "aliasesName": "Digital Currency Group",
        "articles": None,
    },
    {
        "topicName": "Dogecoin",
        "bertieTag": "Dogecoin",
        "forbesMetaDataDescription": "Discover the latest Dogecoin news, analysis, and trends to stay ahead of the game. Find the latest DOGE articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": True,
        "slug": "dogecoin-doge",
        "topicUrl": "/assets/dogecoin-doge",
        "topicOrder": 22,
        "titleTemplate": "Latest Dogecoin USD (DOGE) News | Forbes Digital Assets",
        "description": "Unlock the world of Dogecoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Dogecoin News",
        "aliasesName": "Dogecoin",
        "articles": None,
    },
    {
        "topicName": "Dragonfly",
        "bertieTag": "Dragonfly",
        "forbesMetaDataDescription": "Keep up with the latest Dragonfly news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "dragonfly",
        "topicUrl": "/news/dragonfly",
        "topicOrder": 23,
        "titleTemplate": "Latest Dragonfly News | Forbes Digital Assets",
        "description": "Uncover the latest Dragonfly news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Dragonfly News",
        "aliasesName": "Dragonfly",
        "articles": None,
    },
    {
        "topicName": "Ethereum",
        "bertieTag": "Ethereum",
        "forbesMetaDataDescription": "Discover the latest Ethereum news, analysis, and trends to stay ahead of the game. Find the latest ETH articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "ethereum-eth",
        "topicUrl": "/assets/ethereum-eth",
        "topicOrder": 24,
        "titleTemplate": "Latest Ethereum (ETH) News | Forbes Digital Assets",
        "description": "Unlock the world of Ethereum with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Ethereum News",
        "aliasesName": "Ethereum",
        "articles": None,
    },
    {
        "topicName": "FTX",
        "bertieTag": "FTX",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our FTX news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "ftx-ftt",
        "topicUrl": "/assets/ftx-ftt",
        "topicOrder": 25,
        "titleTemplate": "Latest FTX News | Forbes Digital Assets",
        "description": "Keep up with the newest on FTX. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "FTX News",
        "aliasesName": "FTX",
        "articles": None,
    },
    {
        "topicName": "Filecoin",
        "bertieTag": "Filecoin",
        "forbesMetaDataDescription": "Discover the latest Filecoin news, analysis, and trends to stay ahead of the game. Find the latest FIL articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "filecoin-fil",
        "topicUrl": "/assets/filecoin-fil",
        "topicOrder": 26,
        "titleTemplate": "Latest Filecoin (FIL) News | Forbes Digital Assets",
        "description": "Unlock the world of Filecoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Filecoin News",
        "aliasesName": "Filecoin",
        "articles": None,
    },
    {
        "topicName": "Gemini",
        "bertieTag": "Gemini",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Gemini news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "gemini",
        "topicUrl": "/news/gemini",
        "topicOrder": 27,
        "titleTemplate": "Latest Gemini News | Forbes Digital Assets",
        "description": "Keep up with the newest on Gemini. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Gemini News",
        "aliasesName": "Gemini",
        "articles": None,
    },
    {
        "topicName": "Goldman Sachs",
        "bertieTag": "Goldman Sachs",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge Goldman Sachs crypto news. Discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "goldman-sachs",
        "topicUrl": "/news/goldman-sachs",
        "topicOrder": 28,
        "titleTemplate": "Latest Goldman Sachs Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge Goldman Sachs crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "Goldman Sachs Crypto News",
        "aliasesName": "Goldman Sachs",
        "articles": None,
    },
    {
        "topicName": "HSBC",
        "bertieTag": "HSBC",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge HSBC crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "hsbc",
        "topicUrl": "/news/hsbc",
        "topicOrder": 29,
        "titleTemplate": "Latest HSBC Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge HSBC crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "HSBC Crypto News",
        "aliasesName": "HSBC",
        "articles": None,
    },
    {
        "topicName": "Hedera",
        "bertieTag": "Hedera",
        "forbesMetaDataDescription": "Discover the latest Hedera news, analysis, and trends to stay ahead of the game. Find the latest HBAR articles and important investing insights today.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "hedera-hbar",
        "topicUrl": "/assets/hedera-hbar",
        "topicOrder": 30,
        "titleTemplate": "Latest Hedera (HBAR) News | Forbes Digital Assets",
        "description": "Unlock the world of Hedera with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Hedera News",
        "aliasesName": "Hedera",
        "articles": None,
    },
    {
        "topicName": "IBM",
        "bertieTag": "IBM",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge IBM crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "ibm",
        "topicUrl": "/news/ibm",
        "topicOrder": 31,
        "titleTemplate": "Latest IBM Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge IBM crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "IBM Crypto News",
        "aliasesName": "IBM",
        "articles": None,
    },
    {
        "topicName": "IMF",
        "bertieTag": "IMF",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge IMF crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "imf",
        "topicUrl": "/news/imf",
        "topicOrder": 32,
        "titleTemplate": "Latest IMF News Crypto | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge IMF crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "IMF Crypto News",
        "aliasesName": "IMF",
        "articles": None,
    },
    {
        "topicName": "JPMorgan",
        "bertieTag": "JPMorgan",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge JPMorgan crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "jpmorgan",
        "topicUrl": "/news/jpmorgan",
        "topicOrder": 33,
        "titleTemplate": "Latest JPMorgan Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge JPMorgan crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "JPMorgan Crypto News",
        "aliasesName": "JPMorgan",
        "articles": None,
    },
    {
        "topicName": "Kraken",
        "bertieTag": "Kraken",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Kraken news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "kraken",
        "topicUrl": "/news/kraken",
        "topicOrder": 34,
        "titleTemplate": "Latest Kraken News | Forbes Digital Assets",
        "description": "Keep up with the newest on Kraken. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Kraken News",
        "aliasesName": "Kraken",
        "articles": None,
    },
    {
        "topicName": "KuCoin",
        "bertieTag": "KuCoin",
        "forbesMetaDataDescription": "Kucoin Info",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "kucoin-kcs",
        "topicUrl": "/assets/kucoin-kcs",
        "topicOrder": 35,
        "titleTemplate": "Latest KuCoin News | Forbes Digital Assets",
        "description": "KuCoin News",
        "newsHeader": "KuCoin News",
        "aliasesName": "KuCoin",
        "articles": None,
    },
    {
        "topicName": "Litecoin",
        "bertieTag": "Litecoin",
        "forbesMetaDataDescription": "Discover the latest Litecoin news, analysis, and trends to stay ahead of the game. Find the latest LTC articles and important investing insights today.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "litecoin-ltc",
        "topicUrl": "/assets/litecoin-ltc",
        "topicOrder": 36,
        "titleTemplate": "Latest Litecoin (LTC) News | Forbes Digital Assets",
        "description": "Unlock the world of Litecoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Litecoin News",
        "aliasesName": "Litecoin",
        "articles": None,
    },
    {
        "topicName": "Marathon",
        "bertieTag": "Marathon",
        "forbesMetaDataDescription": "Stay informed with the latest Marathon news. Discover real-time updates, news, analysis, and insights on our Marathon news page.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "marathon",
        "topicUrl": "/news/marathon",
        "topicOrder": 37,
        "titleTemplate": "Latest Marathon News | Forbes Digital Assets",
        "description": "Discover the latest on Marathon. Keep up with the most recent news, innovations, and other updates to stay informed for crypto success.",
        "newsHeader": "Marathon News",
        "aliasesName": "Marathon",
        "articles": None,
    },
    {
        "topicName": "Microsoft",
        "bertieTag": "Microsoft",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge Microsoft crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "microsoft",
        "topicUrl": "/news/microsoft",
        "topicOrder": 38,
        "titleTemplate": "Latest Microsoft Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge Microsoft crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "Microsoft Crypto News",
        "aliasesName": "Microsoft",
        "articles": None,
    },
    {
        "topicName": "Miners",
        "bertieTag": "Miners",
        "forbesMetaDataDescription": "Keep up with the latest Crypto Miner news. Dive into all the updates and expert insights to stay informed on any changes in the world of crypto mining. ",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "miners",
        "topicUrl": "/news/miners",
        "topicOrder": 39,
        "titleTemplate": "Latest Crypto Mining News | Forbes Digital Assets",
        "description": "Unlock the world of Crypto Mining. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Miners News",
        "aliasesName": "Miners",
        "articles": None,
    },
    {
        "topicName": "Multicoin",
        "bertieTag": "Multicoin",
        "forbesMetaDataDescription": "Keep up with the latest Multicoin news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "multicoin",
        "topicUrl": "/news/multicoin",
        "topicOrder": 40,
        "titleTemplate": "Latest Multicoin News | Forbes Digital Assets",
        "description": "Uncover the latest Multicoin news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Multicoin News",
        "aliasesName": "Multicoin",
        "articles": None,
    },
    {
        "topicName": "NFT",
        "bertieTag": "NFT",
        "forbesMetaDataDescription": "Keep up with the latest NFT news. Dive into all the updates and expert insights to stay informed on any changes in the world of NFTs. ",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "nft",
        "topicUrl": "/news/nft",
        "topicOrder": 41,
        "titleTemplate": "Latest NFT News | Forbes Digital Assets",
        "description": "Unleash the power of NFTs. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the NFT world.",
        "newsHeader": "NFT News",
        "aliasesName": "NFT",
        "articles": None,
    },
    {
        "topicName": "OKB",
        "bertieTag": "OKB",
        "forbesMetaDataDescription": "Discover the latest OKB news, analysis, and trends to stay ahead of the game. Find the latest OKB articles and important investing insights today.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "okb-okb",
        "topicUrl": "/assets/okb-okb",
        "topicOrder": 42,
        "titleTemplate": "Latest OKB News | Forbes Digital Assets",
        "description": "Unlock the world of OKB with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "OKB News",
        "aliasesName": "OKB",
        "articles": None,
    },
    {
        "topicName": "Optimism",
        "bertieTag": "Optimism",
        "forbesMetaDataDescription": "Discover the latest Optimism news, analysis, and trends to stay ahead of the game. Find the latest OP articles and important investing insights today.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "optimism-op",
        "topicUrl": "/assets/optimism-op",
        "topicOrder": 43,
        "titleTemplate": "Latest Optimism (OP) News | Forbes Digital Assets",
        "description": "Unlock the world of Optimism with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Optimism News",
        "aliasesName": "Optimism",
        "articles": None,
    },
    {
        "topicName": "Pantera",
        "bertieTag": "Pantera",
        "forbesMetaDataDescription": "Keep up with the latest Pantera news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "pantera",
        "topicUrl": "/news/pantera",
        "topicOrder": 44,
        "titleTemplate": "Latest Pantera News | Forbes Digital Assets",
        "description": "Uncover the latest Pantera news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Pantera News",
        "aliasesName": "Pantera",
        "articles": None,
    },
    {
        "topicName": "PayPal",
        "bertieTag": "PayPal",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our PayPal news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": True,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "paypal",
        "topicUrl": "/news/paypal",
        "topicOrder": 45,
        "titleTemplate": "Latest PayPal News | Forbes Digital Assets",
        "description": "Keep up with the newest on PayPal. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "PayPal News",
        "aliasesName": "PayPal",
        "articles": None,
    },
    {
        "topicName": "Polkadot",
        "bertieTag": "Polkadot",
        "forbesMetaDataDescription": "Discover the latest Polkadot news, analysis, and trends to stay ahead of the game. Find the latest DOT articles and important investing insights today.",
        "isTrending": True,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "polkadot-dot",
        "topicUrl": "/assets/polkadot-dot",
        "topicOrder": 46,
        "titleTemplate": "Latest Polkadot (DOT) News | Forbes Digital Assets",
        "description": "Unlock the world of Polkadot with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Polkadot News",
        "aliasesName": "Polkadot",
        "articles": None,
    },
    {
        "topicName": "Polychain",
        "bertieTag": "Polychain",
        "forbesMetaDataDescription": "Keep up with the latest Polychain news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "polychain",
        "topicUrl": "/news/polychain",
        "topicOrder": 47,
        "titleTemplate": "Latest Polychain News | Forbes Digital Assets",
        "description": "Uncover the latest Polychain news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Polychain News",
        "aliasesName": "Polychain",
        "articles": None,
    },
    {
        "topicName": "Polygon",
        "bertieTag": "Polygon",
        "forbesMetaDataDescription": "Discover the latest Polygon news, analysis, and trends to stay ahead of the game. Find the latest MATIC articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "polygon-matic",
        "topicUrl": "/assets/polygon-matic",
        "topicOrder": 48,
        "titleTemplate": "Latest Polygon (MATIC) News | Forbes Digital Assets",
        "description": "Unlock the world of Polygon with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Polygon News",
        "aliasesName": "Polygon",
        "articles": None,
    },
    {
        "topicName": "Regulation",
        "bertieTag": "Regulation",
        "forbesMetaDataDescription": "Keep up with the latest cryptocurrency regulation news. Dive into all the updates and expert insights to stay informed on any changes in crypto regulation. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "regulation",
        "topicUrl": "/news/regulation",
        "topicOrder": 49,
        "titleTemplate": "Latest Crypto Regulation News | Forbes Digital Assets",
        "description": "Keep up with the latest crypto regulation. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Regulation News",
        "aliasesName": "Regulation",
        "articles": None,
    },
    {
        "topicName": "Riot",
        "bertieTag": "Riot",
        "forbesMetaDataDescription": "Stay informed with the latest Riot news. Discover real-time updates, news, analysis, and insights on our Riot news page.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "riot",
        "topicUrl": "/news/riot",
        "topicOrder": 50,
        "titleTemplate": "Latest Riot News | Forbes Digital Assets",
        "description": "Discover the latest on Riot. Keep up with the most recent news, innovations, and other updates to stay informed for crypto success.",
        "newsHeader": "Riot News",
        "aliasesName": "Riot",
        "articles": None,
    },
    {
        "topicName": "Robinhood",
        "bertieTag": "Robinhood",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Robinhood news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "robinhood",
        "topicUrl": "/news/robinhood",
        "topicOrder": 51,
        "titleTemplate": "Latest Robinhood News | Forbes Digital Assets",
        "description": "Keep up with the newest on Robinhood. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Robinhood News",
        "aliasesName": "Robinhood",
        "articles": None,
    },
    {
        "topicName": "Santander",
        "bertieTag": "Santander",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge Santander crypto news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "santander",
        "topicUrl": "/news/santander",
        "topicOrder": 52,
        "titleTemplate": "Latest Santander Crypto News | Forbes Digital Assets",
        "description": "Stay ahead in the crypto world with cutting-edge Santander crypto news. Look below to discover game-changing insights for your cryptocurrency investing strategies.",
        "newsHeader": "Santander Crypto News",
        "aliasesName": "Santander",
        "articles": None,
    },
    {
        "topicName": "Sequoia",
        "bertieTag": "Sequoia",
        "forbesMetaDataDescription": "Keep up with the latest Sequoia news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "sequoia",
        "topicUrl": "/news/sequoia",
        "topicOrder": 53,
        "titleTemplate": "Latest Sequoia News | Forbes Digital Assets",
        "description": "Uncover the latest Sequoia news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Sequoia News",
        "aliasesName": "Sequoia",
        "articles": None,
    },
    {
        "topicName": "Seven Seven Six",
        "bertieTag": "Seven Seven Six",
        "forbesMetaDataDescription": "Keep up with the latest Seven Seven Six news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "seven-seven-six",
        "topicUrl": "/news/seven-seven-six",
        "topicOrder": 54,
        "titleTemplate": "Latest Seven Seven Six News | Forbes Digital Assets",
        "description": "Uncover the latest Seven Seven Six news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Seven Seven Six News",
        "aliasesName": "Seven Seven Six",
        "articles": None,
    },
    {
        "topicName": "Shiba Inu",
        "bertieTag": "Shiba Inu",
        "forbesMetaDataDescription": "Discover the latest Shiba Inu news, analysis, and trends to stay ahead of the game. Find the latest SHIB articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": True,
        "slug": "shiba-inu-shib",
        "topicUrl": "/assets/shiba-inu-shib",
        "topicOrder": 55,
        "titleTemplate": "Latest Shiba Inu (SHIB) News | Forbes Digital Assets",
        "description": "Unlock the world of Shiba Inu with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Shiba Inu News",
        "aliasesName": "Shiba Inu",
        "articles": None,
    },
    {
        "topicName": "Solana",
        "bertieTag": "Solana",
        "forbesMetaDataDescription": "Discover the latest Solana news, analysis, and trends to stay ahead of the game. Find the latest SOL articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "solana-sol",
        "topicUrl": "/assets/solana-sol",
        "topicOrder": 56,
        "titleTemplate": "Latest Solana (SOL) News | Forbes Digital Assets",
        "description": "Unlock the world of Solana with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Solana News",
        "aliasesName": "Solana",
        "articles": None,
    },
    {
        "topicName": "Stablecoins",
        "bertieTag": "Stablecoins",
        "forbesMetaDataDescription": "Stay ahead in the crypto world with cutting-edge Stablecoin news. Come and discover game-changing insights for your cryptocurrency investing strategies.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "stablecoins",
        "topicUrl": "/news/stablecoins",
        "topicOrder": 57,
        "titleTemplate": "Latest Stablecoin News | Forbes Digital Assets",
        "description": "Unleash the power of Stablecoins. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Stablecoins News",
        "aliasesName": "Stablecoins",
        "articles": None,
    },
    {
        "topicName": "Stronghold Digital",
        "bertieTag": "Stronghold Digital",
        "forbesMetaDataDescription": "Stay informed with the latest Stronghold Digital news. Discover real-time updates, news, analysis, and insights on our Stronghold Digital news page.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "stronghold-digital",
        "topicUrl": "/news/stronghold-digital",
        "topicOrder": 58,
        "titleTemplate": "Latest Stronghold Digital News | Forbes Digital Assets",
        "description": "Discover the latest on Stronghold Digital. Keep up with the most recent news, innovations, and other updates to stay informed for crypto success.",
        "newsHeader": "Stronghold Digital News",
        "aliasesName": "Stronghold Digital",
        "articles": None,
    },
    {
        "topicName": "TRON",
        "bertieTag": "TRON",
        "forbesMetaDataDescription": "Discover the latest TRON news, analysis, and trends to stay ahead of the game. Find the latest TRX articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "tron-trx",
        "topicUrl": "/assets/tron-trx",
        "topicOrder": 59,
        "titleTemplate": "Latest TRON (TRX) News | Forbes Digital Assets",
        "description": "Unlock the world of TRON with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "TRON News",
        "aliasesName": "TRON",
        "articles": None,
    },
    {
        "topicName": "Tether",
        "bertieTag": "Tether",
        "forbesMetaDataDescription": "Stay informed on crypto news. Our Tether news portal brings you the latest updates, analysis, and opinions for the savviest crypto investors.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "tether-usdt",
        "topicUrl": "/assets/tether-usdt",
        "topicOrder": 60,
        "titleTemplate": "Latest Tether News | Forbes Digital Assets",
        "description": "Keep up with the newest on Tether. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the crypto world.",
        "newsHeader": "Tether News",
        "aliasesName": "Tether",
        "articles": None,
    },
    {
        "topicName": "Tezos",
        "bertieTag": "Tezos",
        "forbesMetaDataDescription": "Discover the latest Tezos news, analysis, and trends to stay ahead of the game. Find the latest XTZ articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "tezos-xtz",
        "topicUrl": "/assets/tezos-xtz",
        "topicOrder": 61,
        "titleTemplate": "Latest Tezos (XTZ) News | Forbes Digital Assets",
        "description": "Unlock the world of Tezos with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Tezos News",
        "aliasesName": "Tezos",
        "articles": None,
    },
    {
        "topicName": "TrueUSD",
        "bertieTag": "TrueUSD",
        "forbesMetaDataDescription": "Discover the latest TrueUSD news, analysis, and trends to stay ahead of the game. Find the latest TUSD articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "Trueusd-tusd",
        "topicUrl": "/assets/Trueusd-tusd",
        "topicOrder": 62,
        "titleTemplate": "Latest True USD (TUSD) News | Forbes Digital Assets",
        "description": "Unlock the world of TrueUSD with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "TrueUSD News",
        "aliasesName": "TrueUSD",
        "articles": None,
    },
    {
        "topicName": "USDC",
        "bertieTag": "USDC",
        "forbesMetaDataDescription": "Discover the latest USCoin news, analysis, and trends to stay ahead of the game. Find the latest USDC articles and important investing insights today.",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "usd-coin-usdc",
        "topicUrl": "/news/usd-coin-usdc",
        "topicOrder": 63,
        "titleTemplate": "Latest USCoin (USDC) News | Forbes Digital Assets",
        "description": "Unlock the world of USCoin with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "USDC News",
        "aliasesName": "USD Coin",
        "articles": None,
    },
    {
        "topicName": "USDT",
        "bertieTag": "USDT",
        "forbesMetaDataDescription": "Discover the latest Tether USD news, analysis, and trends to stay ahead of the game. Find the latest USDT articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "tether-usdt",
        "topicUrl": "/assets/tether-usdt",
        "topicOrder": 64,
        "titleTemplate": "Latest Tether USD (USDT) News | Forbes Digital Assets",
        "description": "Unlock the world of Tether USD with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "USDT News",
        "aliasesName": "Tether",
        "articles": None,
    },
    {
        "topicName": "Union Square Ventures",
        "bertieTag": "Union Square Ventures",
        "forbesMetaDataDescription": "Keep up with the latest Union Square news. Dive into all the updates and expert insights to stay informed on any changes in the cryptocurrency market. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "union-square",
        "topicUrl": "/news/union-square",
        "topicOrder": 65,
        "titleTemplate": "Latest Union Square News | Forbes Digital Assets",
        "description": "Uncover the latest Union Square news. Dive into the newest trend updates, analysis, news, and crypto market updates below. ",
        "newsHeader": "Union Square News",
        "aliasesName": "Union Square",
        "articles": None,
    },
    {
        "topicName": "Uniswap",
        "bertieTag": "Uniswap",
        "forbesMetaDataDescription": "Discover the latest Uniswap news, analysis, and trends to stay ahead of the game. Find the latest UNI articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "uniswap-uni",
        "topicUrl": "/assets/uniswap-uni",
        "topicOrder": 66,
        "titleTemplate": "Latest Uniswap (UNI) News | Forbes Digital Assets",
        "description": "Unlock the world of Uniswap with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "Uniswap News",
        "aliasesName": "Uniswap",
        "articles": None,
    },
    {
        "topicName": "VeChain",
        "bertieTag": "VeChain",
        "forbesMetaDataDescription": "Discover the latest VeChain news, analysis, and trends to stay ahead of the game. Find the latest VET articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": False,
        "slug": "vechain-vet",
        "topicUrl": "/assets/vechain-vet",
        "topicOrder": 67,
        "titleTemplate": "Latest VeChain (VET) News | Forbes Digital Assets",
        "description": "Unlock the world of VeChain with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "VeChain News",
        "aliasesName": "VeChain",
        "articles": None,
    },
    {
        "topicName": "Web3",
        "bertieTag": "Web3",
        "forbesMetaDataDescription": "Keep up with the latest Web3 news. Dive into all the updates and expert insights to stay informed on any advances in the world of Web3. ",
        "isTrending": False,
        "isAsset": False,
        "isFeaturedHome": False,
        "slug": "web3",
        "topicUrl": "/news/web3",
        "topicOrder": 68,
        "titleTemplate": "Latest Web3 News | Forbes Digital Assets",
        "description": "Uncover everything Web3. Dive into the latest news and updates to stay informed, maximize opportunities, and drive success in the world of Web3.",
        "newsHeader": "Web3 News",
        "aliasesName": "Web3",
        "articles": None,
    },
    {
        "topicName": "XRP",
        "bertieTag": "XRP",
        "forbesMetaDataDescription": "Discover the latest Ripple USD news, analysis, and trends to stay ahead of the game. Find the latest XRP articles and important investing insights today.",
        "isTrending": False,
        "isAsset": True,
        "isFeaturedHome": True,
        "slug": "xrp-xrp",
        "topicUrl": "/assets/xrp-xrp",
        "topicOrder": 69,
        "titleTemplate": "Latest Ripple USD (XRP) News | Forbes Digital Assets",
        "description": "Unlock the world of Ripple with our latest news hub. Dive into the latest trends, crypto market updates, and analysis and news articles below.  ",
        "newsHeader": "XRP News",
        "aliasesName": "XRP",
        "articles": None,
    },
]

new_list = list()
for item in d:
    for i in d2:
        if item["NewsTag"] == i["topicName"]:
            new_dict = dict()
            new_dict["Category"] = item["Category"]
            new_dict["NewsTag"] = item["NewsTag"]
            new_dict["NewsPageMetaTitle"] = item["NewsPageMetaTitle"]
            new_dict["NewsPageMetaDescription"] = item["NewsPageMetaDescription"]
            new_dict["NewsPageH1"] = item["NewsPageH1"]
            new_dict["description"] = i["description"]
            new_list.append(new_dict)

with open("data_new_list2.json", "w") as file:
    file.write(json.dumps(new_list))
