"""create_fk_tracking

Revision ID: 9eb0b6a3a702
Revises: 5f9031a018c0
Create Date: 2024-04-08 02:26:48.373615

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9eb0b6a3a702"
down_revision: Union[str, None] = "5f9031a018c0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tracking", sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False)
    )
    op.create_foreign_key("fk_tracking_user", "tracking", "users", ["user_id"], ["id"])


def downgrade() -> None:
    op.drop_constraint('fk_tracking_user', 'tracking', type_='foreignkey')
    op.drop_column('tracking', 'user_id')
