Create Table "transitions" (
    chain_id BIGINT,
    id TEXT,
    log_index BIGINT,
    transaction_hash TEXT,
    transaction_index BIGINT,
    address TEXT,
    creator_address TEXT,
    tx_from_address TEXT,
    data TEXT,
    topics TEXT[],
    block_timestamp TIMESTAMPTZ,
    block_number BIGINT,
    block_hash TEXT,
    signature TEXT,
    from_address TEXT,
    to_address TEXT,
    to_creator_address TEXT,
    to_tx_from_address TEXT,
    decoded JSONB,
    decoded_error TEXT,
    is_decoded BOOLEAN,
    value_lossless numeric,
    value DOUBLE PRECISION,
    nonce BIGINT,
    gas BIGINT,
    gas_price BIGINT,
    input TEXT,
    receipt_cumulative_gas_used BIGINT,
    receipt_gas_used BIGINT,
    receipt_contract_address TEXT,
    receipt_root TEXT,
    receipt_status BIGINT,
    max_fee_per_gas BIGINT,
    max_priority_fee_per_gas BIGINT,
    transaction_type BIGINT,
    receipt_effective_gas_price BIGINT,
    fee DOUBLE PRECISION,
    txn_saving BIGINT,
    burned_fee DOUBLE PRECISION,
    method_id TEXT,
    r TEXT,
    s TEXT,
    v TEXT,
    access_list JSONB,
    value_usd DOUBLE PRECISION,
    fee_usd DOUBLE PRECISION
);