SELECT SYMBOL,
	DISPLAY_SYMBOL,
	SLUG,
	STATUS,
	MARKET_CAP,
	PRICE_24H,
	NUMBER_OF_ACTIVE_MARKET_PAIRS,
	COINPAPRIKA_ID,
	COINGECKO_ID,
	DESCRIPTION,
	NAME,
	WEBSITE_URL,
	BLOG_URL,
	DISCORD_URL,
	FACEBOOK_URL,
	GITHUB_URL,
	MEDIUM_URL,
	REDDIT_URL,
	TELEGRAM_URL,
	TWITTER_URL,
	WHITEPAPER_URL,
	YOUTUBE_URL,
	BITCOINTALK_URL,
	BLOCKEXPLORER_URL
FROM
	(SELECT SYMBOL,
			DISPLAY_SYMBOL,
			SLUG,
			STATUS,
			MARKET_CAP,
			PRICE_24H,
			NUMBER_OF_ACTIVE_MARKET_PAIRS
		FROM FUNDAMENTALSLATEST
		WHERE SLUG = 'xsgd-xsgd' ) A
LEFT JOIN
	(SELECT ID,
			COINPAPRIKA_ID,
			COINGECKO_ID
		FROM FORBES_ASSETS
		WHERE COINPAPRIKA_ID IS NOT NULL ) B ON A.SLUG = B.ID
LEFT JOIN
	(SELECT ID,
			DESCRIPTION,
			NAME,
			(LINKS::JSON - >> 'website')::text AS WEBSITE_URL,
			(LINKS::JSON - >> 'blog')::text AS BLOG_URL,
			(LINKS::JSON - >> 'discord')::text AS DISCORD_URL,
			(LINKS::JSON - >> 'facebook')::text AS FACEBOOK_URL,
			(LINKS::JSON - >> 'source_code')::text AS GITHUB_URL,
			(LINKS::JSON - >> 'medium')::text AS MEDIUM_URL,
			(LINKS::JSON - >> 'reddit')::text AS REDDIT_URL,
			(LINKS::JSON - >> 'telegram')::text AS TELEGRAM_URL,
			(LINKS::JSON - >> 'twitter')::text AS TWITTER_URL,
			(WHITEPAPER::JSON - >> 'link')::text AS WHITEPAPER_URL,
			(LINKS::JSON - >> 'youtube')::text AS YOUTUBE_URL,
			(LINKS::JSON - >> 'message_board')::text AS BITCOINTALK_URL,
			(LINKS::JSON - >> 'explorer')::JSON - >> 0 AS BLOCKEXPLORER_URL
		FROM COINPAPRIKA_ASSET_METADATA) META ON B.COINPAPRIKA_ID = META.ID