package datastruct

import (
	"fmt"
	"os"
)

var CustomCategoryTable = fmt.Sprintf("%s%s", os.Getenv("ROWY_PREFIX"), "test_custom_category")

type CustomCategoryRequest struct {
	CategoryName   string   `json:"categoryName,omitempty" firestore:"categoryName"`
	PlatformId     string   `json:"platformId,omitempty" firestore:"platformId"`
	Assets         []string `json:"assets,omitempty" firestore:"assets"`
	TableName      string   `json:"tableName,omitempty" firestore:"tableName"`
	Column         string   `json:"column,omitempty" firestore:"column"`
	Sort           string   `json:"sort,omitempty" firestore:"sort"`
	Limit          int      `json:"limit,omitempty" firestore:"limit"`
	Condition      string   `json:"condition,omitempty" firestore:"condition"`
	ConditionValue string   `json:"conditionValue,omitempty" firestore:"conditionValue"`
}

type CustomCategory struct {
	Symbol string `json:"symbol" postgresql:"symbol"`
	Name   string `json:"name" postgresql:"name"`
	Slug   string `json:"slug" postgresql:"slug"`
}

var FundamentalsColumns string = `
SELECT
	symbol,
	name,
	slug,
	logo,
	float_type,
	display_symbol,
	original_symbol,
	source,
	temporary_data_delay,
	number_of_active_market_pairs,
	high_24h,
	low_24h,
	high_7d,
	low_7d,
	high_30d,
	low_30d,
	high_1y,
	low_1y,
	high_ytd,
	low_ytd,
	price_24h,
	price_7d,
	price_30d,
	price_1y,
	price_ytd,
	percentage_1h,
	percentage_24h,
	percentage_7d,
	percentage_30d,
	percentage_1y,
	percentage_ytd,
	market_cap,
	market_cap_percent_change_1d,
	market_cap_percent_change_7d,
	market_cap_percent_change_30d,
	market_cap_percent_change_1y,
	market_cap_percent_change_ytd,
	circulating_supply,
	supply,
	all_time_low,
	all_time_high,
	date,
	change_value_24h,
	listed_exchange,
	market_pairs,
	exchanges,
	nomics,
	forbes,
	last_updated
`
var NFTColumns string = `
SELECT 
	id,
	contract_address,
	asset_platform_id,
	name,
	symbol,
	symbol as display_symbol,
	image,
	large_image,
	description,
	native_currency,
	floor_price_usd,
	market_cap_usd,
	volume_24h_usd,
	floor_price_native,
	market_cap_native,
	volume_24h_native,
	floor_price_in_usd_24h_percentage_change,
	volume_24h_percentage_change_usd,
	number_of_unique_addresses,
	number_of_unique_addresses_24h_percentage_change,
	slug,
	total_supply,
	website_url,
	twitter_url,
	discord_url,
	explorers,
	last_updated,
	avg_sale_price_1d,
	avg_sale_price_7d,
	avg_sale_price_30d,
	avg_sale_price_90d,
	avg_sale_price_ytd,
	avg_total_sales_pct_change_1d,
	avg_total_sales_pct_change_7d,
	avg_total_sales_pct_change_30d,
	avg_total_sales_pct_change_90d,
	avg_total_sales_pct_change_ytd,
	total_sales_1d,
	total_sales_7d,
	total_sales_30d,
	total_sales_90d,
	total_sales_ytd,
	avg_sales_price_change_1d,
	avg_sales_price_change_7d,
	avg_sales_price_change_30d,
	avg_sales_price_change_90d,
	avg_sales_price_change_ytd,
	native_currency_symbol,
	market_cap_24h_percentage_change_usd,
	market_cap_24h_percentage_change_native,
	volume_24h_percentage_change_native,
	volume_usd_1d,
	volume_usd_7d,
	volume_usd_30d,
	volume_usd_90d,
	volume_usd_ytd,
	volume_native_1d,
	volume_native_7d,
	volume_native_30d,
	volume_native_90d,
	volume_native_ytd,
	pct_change_volume_usd_1d,
	pct_change_volume_usd_7d,
	pct_change_volume_usd_30d,
	pct_change_volume_usd_90d,
	pct_change_volume_usd_ytd,
	pct_change_volume_native_1d,
	pct_change_volume_native_7d,
	pct_change_volume_native_30d,
	pct_change_volume_native_90d,
	pct_change_volume_native_ytd,
	lowest_floor_price_24h_usd,
	highest_floor_price_24h_usd,
	lowest_floor_price_24h_native,
	highest_floor_price_24h_native,
	floor_price_24h_percentage_change_usd,
	floor_price_24h_percentage_change_native,
	lowest_floor_price_24h_percentage_change_usd,
	lowest_floor_price_24h_percentage_change_native,
	highest_floor_price_24h_percentage_change_usd,
	highest_floor_price_24h_percentage_change_native,
	lowest_floor_price_7d_usd,
	highest_floor_price_7d_usd,
	lowest_floor_price_7d_native,
	highest_floor_price_7d_native,
	floor_price_7d_percentage_change_usd,
	floor_price_7d_percentage_change_native,
	lowest_floor_price_7d_percentage_change_usd,
	lowest_floor_price_7d_percentage_change_native,
	highest_floor_price_7d_percentage_change_usd,
	highest_floor_price_7d_percentage_change_native,
	lowest_floor_price_30d_usd,
	highest_floor_price_30d_usd,
	lowest_floor_price_30d_native,
	highest_floor_price_30d_native,
	floor_price_30d_percentage_change_usd,
	floor_price_30d_percentage_change_native,
	lowest_floor_price_30d_percentage_change_usd,
	lowest_floor_price_30d_percentage_change_native,
	highest_floor_price_30d_percentage_change_usd,
	highest_floor_price_30d_percentage_change_native,
	lowest_floor_price_90d_usd,
	highest_floor_price_90d_usd,
	lowest_floor_price_90d_native,
	highest_floor_price_90d_native,
	floor_price_90d_percentage_change_usd,
	floor_price_90d_percentage_change_native,
	lowest_floor_price_90d_percentage_change_usd,
	lowest_floor_price_90d_percentage_change_native,
	highest_floor_price_90d_percentage_change_usd,
	highest_floor_price_90d_percentage_change_native,
	lowest_floor_price_ytd_usd,
	highest_floor_price_ytd_usd,
	lowest_floor_price_ytd_native,
	highest_floor_price_ytd_native,
	floor_price_ytd_percentage_change_usd,
	floor_price_ytd_percentage_change_native,
	lowest_floor_price_ytd_percentage_change_usd,
	lowest_floor_price_ytd_percentage_change_native,
	highest_floor_price_ytd_percentage_change_usd,
	highest_floor_price_ytd_percentage_change_native
`
var CategoryColumns string = `
SELECT 
	id,
	name,
	total_tokens,
	average_percentage_24h,
	volume_24h,
	price_24h,
	average_price,
	market_cap,
	market_cap_percentage_24h,
	top_gainers,
	top_movers,
	"forbesName" as forbesName,
	slug,
	last_updated,
	is_highlighted
`
